// web/src/lib/components/project-switcher.svelte
<script lang="ts">
  import { goto } from "$app/navigation";
  import ArrowLeftRight from "@lucide/svelte/icons/arrow-left-right";
  import Check from "@lucide/svelte/icons/check";
  import Plus from "@lucide/svelte/icons/plus";
  import Settings from "@lucide/svelte/icons/settings";

  import { Button } from "$lib/components/ui/button";
  import * as Popover from "$lib/components/ui/popover";
  import { MENU_ITEM_CLASS, POPOVER_SURFACE_CLASS } from "$lib/control-styles";
  import {
    activeVault,
    switchVault,
    useVaults,
  } from "$lib/hooks/use-vault.svelte";

  const vaults = useVaults();
  let open = $state(false);

  const list = $derived(vaults.data ?? []);
  const isEmpty = $derived(list.length === 0);
  const triggerLabel = $derived(isEmpty ? "new project" : "switch project");

  function createProject() {
    open = false;
    void goto("/vaults/new");
  }

  function chooseVault(vaultId: string) {
    if (vaultId !== activeVault.id) {
      switchVault(vaultId);
      void goto("/");
    }
    open = false;
  }

  function openSettings(vaultId: string) {
    open = false;
    void goto(`/project/${vaultId}/settings`);
  }
</script>

{#if !vaults.isLoading}
  {#if isEmpty}
    <Button
      variant="ghost"
      size="icon-sm"
      aria-label={triggerLabel}
      onclick={createProject}
      class="rounded-sm text-warm-ghost hover:bg-ink-raised hover:text-warm-faint"
    >
      <Plus class="size-3.5" />
    </Button>
  {:else}
    <Popover.Root bind:open>
      <Popover.Trigger>
        {#snippet child({ props })}
          <Button
            {...props}
            variant="ghost"
            size="icon-sm"
            aria-label={triggerLabel}
            class="rounded-sm text-warm-ghost hover:bg-ink-raised hover:text-warm-faint"
          >
            <ArrowLeftRight class="size-3.5" />
          </Button>
        {/snippet}
      </Popover.Trigger>
      <Popover.Content
        side="bottom"
        align="end"
        sideOffset={8}
        class={`w-auto min-w-[220px] p-1 ${POPOVER_SURFACE_CLASS}`}
      >
        {#each list as vault (vault.id)}
          <div class="group flex items-center">
            <Button
              variant="ghost"
              size="sm"
              onclick={() => chooseVault(vault.id)}
              class={`${MENU_ITEM_CLASS} flex-1 justify-start gap-2`}
            >
              {#if vault.id === activeVault.id}
                <Check class="size-3.5" />
              {:else}
                <span class="size-3.5"></span>
              {/if}
              {vault.name}
            </Button>
            {#if vault.id === activeVault.id}
              <Button
                variant="ghost"
                size="icon-xs"
                onclick={() => openSettings(vault.id)}
                aria-label="project settings"
                class="mr-1 text-warm-ghost opacity-0 transition-opacity group-hover:opacity-100 hover:bg-transparent hover:text-gold focus-visible:opacity-100"
              >
                <Settings size={11} />
              </Button>
            {/if}
          </div>
        {/each}
        <div class="my-1 border-t border-ink-border"></div>
        <Button
          variant="ghost"
          size="sm"
          onclick={createProject}
          class={`${MENU_ITEM_CLASS} w-full justify-start gap-2`}
        >
          <Plus class="size-3.5" />
          new project
        </Button>
      </Popover.Content>
    </Popover.Root>
  {/if}
{/if}

// web/src/containers/project-switcher.tsx
import { useState } from "react";
import { ArrowLeftRight, Check, Plus, Settings } from "lucide-react";
import { useNavigate } from "react-router";

import { Button } from "@/components/ui/button";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { MENU_ITEM_CLASS, POPOVER_SURFACE_CLASS } from "@/lib/control-styles";
import { useActiveVaultId, useVaults, useSwitchVault } from "@/hooks/use-vault";

const ITEM_CLASS = `${MENU_ITEM_CLASS} gap-2 flex-1 justify-start`;

export function ProjectSwitcher() {
  const navigate = useNavigate();
  const { data: vaults, isLoading } = useVaults();
  const activeVaultId = useActiveVaultId();
  const switchVault = useSwitchVault();

  const [open, setOpen] = useState(false);

  if (isLoading) return null;

  const list = vaults ?? [];
  const isEmpty = list.length === 0;
  const Icon = isEmpty ? Plus : ArrowLeftRight;
  const triggerLabel = isEmpty ? "new project" : "switch project";

  function handleCreate() {
    setOpen(false);
    navigate("/vaults/new");
  }

  function handleSwitch(vaultId: string) {
    if (vaultId !== activeVaultId) {
      switchVault(vaultId);
      navigate("/");
    }
    setOpen(false);
  }

  function handleSettings(vaultId: string) {
    setOpen(false);
    navigate(`/project/${vaultId}/settings`);
  }

  if (isEmpty) {
    return (
      <Button
        variant="ghost"
        size="icon-sm"
        aria-label={triggerLabel}
        onClick={handleCreate}
        className="text-warm-ghost hover:text-warm-faint hover:bg-ink-raised rounded-sm"
      >
        <Icon className="size-3.5" />
      </Button>
    );
  }

  return (
    <Popover open={open} onOpenChange={setOpen}>
      <PopoverTrigger
        render={
          <Button
            variant="ghost"
            size="icon-sm"
            aria-label={triggerLabel}
            className="text-warm-ghost hover:text-warm-faint hover:bg-ink-raised rounded-sm"
          />
        }
      >
        <Icon className="size-3.5" />
      </PopoverTrigger>
      <PopoverContent
        side="bottom"
        align="end"
        sideOffset={8}
        className={`w-auto min-w-[220px] p-1 ${POPOVER_SURFACE_CLASS}`}
      >
        {list.map((vault) => {
          const isActive = vault.id === activeVaultId;
          return (
            <div key={vault.id} className="flex items-center group">
              <Button
                variant="ghost"
                size="sm"
                onClick={() => handleSwitch(vault.id)}
                className={ITEM_CLASS}
              >
                {isActive ? <Check className="size-3.5" /> : <span className="size-3.5" />}
                {vault.name}
              </Button>
              {isActive && (
                <Button
                  variant="ghost"
                  size="icon-xs"
                  onClick={() => handleSettings(vault.id)}
                  aria-label="project settings"
                  className="text-warm-ghost hover:text-gold hover:bg-transparent opacity-0 group-hover:opacity-100 transition-opacity mr-1"
                >
                  <Settings size={11} />
                </Button>
              )}
            </div>
          );
        })}
        <div className="my-1 border-t border-ink-border" />
        <Button variant="ghost" size="sm" onClick={handleCreate} className={`${ITEM_CLASS} w-full`}>
          <Plus className="size-3.5" />
          new project
        </Button>
      </PopoverContent>
    </Popover>
  );
}
