// web/src/lib/components/article-panel.svelte
<script lang="ts">
  import Maximize2 from "@lucide/svelte/icons/maximize-2";
  import X from "@lucide/svelte/icons/x";

  import { Button } from "$lib/components/ui/button";
  import { Skeleton } from "$lib/components/ui/skeleton";
  import MarkdownView from "$lib/components/markdown-view.svelte";
  import type { PanelContent } from "$lib/panel-content";
  import type { SourceRef } from "$lib/types";
  import { displayTitle } from "$lib/utils";

  let {
    card,
    content,
    loading,
    onClose,
    onFullScreen,
    onOpenPath,
  }: {
    card: SourceRef;
    content: PanelContent | null;
    loading: boolean;
    onClose: () => void;
    onFullScreen: () => void;
    onOpenPath: (path: string) => void;
  } = $props();

  const headingTitle = $derived(displayTitle(card.label, card.title));
  const subtitle = $derived.by(() => {
    if (card.type === "links") return "connections the agent saw";
    if (content?.mode === "chunks") {
      const ranges = (card.ranges ?? [])
        .map((range) =>
          range.start === range.end
            ? `¶${range.start}`
            : `¶${range.start}–${range.end}`,
        )
        .join(", ");
      return ranges ? `${ranges} · what the agent read` : "what the agent read";
    }
    const kind = card.label.startsWith("wiki/") ? "wiki article" : "raw source";
    return `${kind} · full document`;
  });
</script>

<div class="flex h-full flex-col">
  <div class="shrink-0 border-b border-ink-subtle px-5 pt-5 pb-3.5">
    <div class="mb-[9px] flex items-start justify-between gap-2">
      <span
        class="min-w-0 break-words text-[length:var(--text-body)] font-bold text-foreground"
      >
        {headingTitle}
      </span>
      <div class="flex shrink-0 items-center gap-1">
        <Button
          variant="ghost"
          size="icon-xs"
          onclick={onFullScreen}
          class="shrink-0 text-muted-foreground hover:bg-transparent hover:text-gold"
          title="Open full screen"
          aria-label="open full screen"
        >
          <Maximize2 size={12} />
        </Button>
        <Button
          variant="ghost"
          size="icon-xs"
          onclick={onClose}
          class="shrink-0 text-muted-foreground hover:bg-transparent hover:text-warm-faint"
          aria-label="close article panel"
        >
          <X size={14} />
        </Button>
      </div>
    </div>
    <span
      title={card.label}
      class="font-mono text-[length:var(--text-chrome)] tracking-[0.1em] text-interactive-dim uppercase"
    >
      {subtitle}
    </span>
  </div>

  <div class="min-h-0 flex-1 overflow-y-auto">
    <div class="px-5 py-[18px]">
      {#if loading}
        <div class="space-y-3">
          <Skeleton class="h-4 w-full bg-ink-raised" />
          <Skeleton class="h-4 w-11/12 bg-ink-raised" />
          <Skeleton class="h-4 w-4/5 bg-ink-raised" />
          <Skeleton class="h-4 w-2/3 bg-ink-raised" />
        </div>
      {:else if content?.mode === "doc"}
        <MarkdownView source={content.body} variant="panel" stripBlockRefs />
      {:else if content?.mode === "chunks"}
        <div class="space-y-5">
          {#if content.chunks.length === 0}
            <p class="text-[length:var(--text-small)] text-warm-faint">
              No passages found.
            </p>
          {:else}
            {#each content.chunks as chunk (chunk.chunk_index)}
              <div>
                <div
                  class="mb-1 font-mono text-[length:var(--text-chrome)] tracking-[0.08em] text-gold-muted"
                >
                  ¶{chunk.chunk_index}{chunk.heading
                    ? ` · ${chunk.heading}`
                    : ""}
                </div>
                <MarkdownView
                  source={chunk.body}
                  variant="panel"
                  stripBlockRefs
                />
              </div>
            {/each}
          {/if}
        </div>
      {:else if content?.mode === "links"}
        <div class="space-y-5">
          {#each [{ label: "cites →", items: content.links.outgoing }, { label: "cited by ←", items: content.links.incoming }] as group (group.label)}
            <div>
              <div
                class="mb-2 font-mono text-[length:var(--text-chrome)] tracking-[0.1em] text-interactive-dim uppercase"
              >
                {group.label}
              </div>
              {#if group.items.length === 0}
                <p
                  class="text-[length:var(--text-small)] text-warm-ghost italic"
                >
                  none
                </p>
              {:else}
                <ul class="space-y-1">
                  {#each group.items as item (item.file_path)}
                    <li>
                      <button
                        type="button"
                        onclick={() => onOpenPath(item.file_path)}
                        class="text-left text-[length:var(--text-small)] text-warm-dim transition-colors hover:text-gold"
                      >
                        {item.title}
                      </button>
                    </li>
                  {/each}
                </ul>
              {/if}
            </div>
          {/each}
        </div>
      {:else}
        <p class="text-[length:var(--text-small)] text-warm-faint">
          Not found.
        </p>
      {/if}
    </div>
  </div>
</div>

// web/src/components/article-panel.tsx
import { Maximize2, X } from "lucide-react";
import Markdown from "react-markdown";

import { remarkPlugins } from "@/lib/markdown";
import { displayTitle } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";

interface ArticlePanelProps {
  path: string;
  title: string | null;
  kind: "raw" | "wiki" | null;
  body: string | null;
  loading: boolean;
  onClose: () => void;
  onFullScreen: () => void;
}

export function ArticlePanel({
  path,
  title,
  kind,
  body,
  loading,
  onClose,
  onFullScreen,
}: ArticlePanelProps) {
  const headingTitle = displayTitle(path, title);

  return (
    <div className="fixed top-0 right-0 w-full md:w-[370px] h-screen bg-ink-panel border-l border-ink-subtle flex flex-col z-[200] shadow-none md:shadow-[-24px_0_60px_rgba(80,60,30,0.12)] dark:md:shadow-[-24px_0_60px_rgba(0,0,0,0.6)] animate-[panel-in_0.28s_cubic-bezier(0.4,0,0.2,1)]">
      <div className="px-5 pt-5 pb-3.5 border-b border-ink-subtle shrink-0">
        <div className="flex items-start justify-between gap-2 mb-[9px]">
          <span className="text-[length:var(--text-body)] font-bold text-foreground min-w-0 break-words">
            {headingTitle}
          </span>
          <div className="flex items-center gap-1 shrink-0">
            <Button
              variant="ghost"
              size="icon-xs"
              onClick={onFullScreen}
              className="text-muted-foreground hover:text-gold hover:bg-transparent shrink-0"
              title="Open full screen"
            >
              <Maximize2 size={12} />
            </Button>
            <Button
              variant="ghost"
              size="icon-xs"
              onClick={onClose}
              className="text-muted-foreground hover:text-warm-faint hover:bg-transparent shrink-0"
            >
              <X size={14} />
            </Button>
          </div>
        </div>
        {kind && (
          <span
            title={path}
            className="font-mono text-[length:var(--text-chrome)] tracking-[0.1em] uppercase text-interactive-dim"
          >
            {kind}
          </span>
        )}
      </div>

      <div className="flex-1 min-h-0 overflow-y-auto">
        <div className="px-5 py-[18px]">
          {loading && (
            <div className="space-y-3">
              <Skeleton className="h-4 w-full bg-ink-raised" />
              <Skeleton className="h-4 w-11/12 bg-ink-raised" />
              <Skeleton className="h-4 w-4/5 bg-ink-raised" />
              <Skeleton className="h-4 w-full bg-ink-raised" />
              <Skeleton className="h-4 w-2/3 bg-ink-raised" />
            </div>
          )}
          {!loading && body && (
            <div className="text-[length:var(--text-small)] leading-[1.76] text-warm-faint [&_p]:mb-[13px] [&_h2]:text-[length:var(--text-body)] [&_h2]:font-bold [&_h2]:text-foreground [&_h2]:mt-5 [&_h2]:mb-2 [&_h3]:text-[length:var(--text-caption)] [&_h3]:font-mono [&_h3]:text-gold [&_h3]:tracking-[0.1em] [&_h3]:uppercase [&_h3]:mt-4 [&_h3]:mb-2">
              <Markdown remarkPlugins={remarkPlugins}>{body}</Markdown>
            </div>
          )}
          {!loading && !body && (
            <p className="text-[length:var(--text-small)] text-warm-faint">Article not found.</p>
          )}
        </div>
      </div>
    </div>
  );
}
