// web/src/lib/components/article-chrome.svelte
<script lang="ts">
  import Home from "@lucide/svelte/icons/home";
  import type { Snippet } from "svelte";

  import { Button } from "$lib/components/ui/button";
  import { Input } from "$lib/components/ui/input";

  let {
    label,
    onHome,
    onQuery,
    children,
    footer,
  }: {
    label: string;
    onHome: () => void;
    onQuery: (question: string) => void;
    children: Snippet;
    footer?: Snippet;
  } = $props();

  let queryText = $state("");

  function submit() {
    const question = queryText.trim();
    if (!question) return;
    onQuery(question);
    queryText = "";
  }

  function handleKeydown(event: KeyboardEvent) {
    if (event.key === "Enter") submit();
    if (event.key === "Escape") {
      queryText = "";
      (event.currentTarget as HTMLInputElement).blur();
    }
  }
</script>

<div class="flex h-screen flex-col overflow-hidden">
  <header
    class="flex shrink-0 items-center justify-between gap-3 border-b border-ink-subtle px-4 pt-4 pb-3 md:px-6"
  >
    <div class="flex shrink-0 items-center gap-4">
      <Button
        variant="ghost"
        size="icon-xs"
        onclick={onHome}
        aria-label="home"
        class="text-muted-foreground hover:bg-transparent hover:text-gold"
      >
        <Home size={14} />
      </Button>
      <span
        class="hidden font-mono text-[length:var(--text-chrome)] tracking-[0.14em] text-gold-muted uppercase md:inline"
      >
        {label}
      </span>
    </div>

    <div
      class="flex max-w-[400px] flex-1 items-center overflow-hidden rounded-sm border border-input bg-secondary focus-within:border-ring"
    >
      <Input
        bind:value={queryText}
        onkeydown={handleKeydown}
        class="h-auto flex-1 rounded-none border-none bg-transparent px-3 py-[9px] font-serif text-[length:var(--text-small)] text-foreground caret-gold placeholder:text-input focus-visible:border-none focus-visible:ring-0 dark:bg-transparent"
        placeholder="Ask about this article..."
        aria-label="ask about this article"
      />
      <Button
        onclick={submit}
        disabled={!queryText.trim()}
        class="h-auto rounded-none bg-gold px-3 py-[9px] font-mono text-[length:var(--text-chrome)] font-medium tracking-[0.12em] text-primary-foreground hover:bg-gold-hover disabled:bg-interactive-ghost disabled:text-muted-foreground disabled:opacity-100"
      >
        QUERY
      </Button>
    </div>
  </header>

  <div class="min-h-0 flex-1 overflow-y-auto">
    {@render children()}
  </div>

  {#if footer}
    {@render footer()}
  {/if}
</div>

// web/src/components/article-chrome.tsx
import { useState, useCallback } from "react";
import { Home } from "lucide-react";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

interface ArticleChromeProps {
  label: string;
  onHome: () => void;
  onQuery: (question: string) => void;
  onContentClick?: React.MouseEventHandler;
  footer?: React.ReactNode;
  children: React.ReactNode;
}

export function ArticleChrome({
  label,
  onHome,
  onQuery,
  onContentClick,
  footer,
  children,
}: ArticleChromeProps) {
  const [queryText, setQueryText] = useState("");

  const handleSubmit = useCallback(() => {
    if (!queryText.trim()) return;
    onQuery(queryText.trim());
    setQueryText("");
  }, [queryText, onQuery]);

  return (
    <div className="h-screen flex flex-col overflow-hidden">
      <div className="shrink-0 flex items-center justify-between px-4 md:px-6 pt-4 pb-3 border-b border-ink-subtle gap-3">
        <div className="flex items-center gap-4 shrink-0">
          <Button
            variant="ghost"
            size="icon-xs"
            onClick={onHome}
            className="text-muted-foreground hover:text-gold hover:bg-transparent"
          >
            <Home size={14} />
          </Button>
          <span className="font-mono text-[length:var(--text-chrome)] tracking-[0.14em] text-gold-muted uppercase hidden md:inline">
            {label}
          </span>
        </div>

        <div className="flex items-center flex-1 max-w-[400px] bg-secondary border border-input rounded-sm overflow-hidden focus-within:border-ring">
          <Input
            className="flex-1 h-auto border-none rounded-none bg-transparent dark:bg-transparent font-serif text-[length:var(--text-small)] text-foreground px-3 py-[9px] caret-gold placeholder:text-input focus-visible:ring-0 focus-visible:border-none"
            placeholder="Ask about this article..."
            value={queryText}
            onChange={(e) => setQueryText(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === "Enter") handleSubmit();
              if (e.key === "Escape") {
                setQueryText("");
                (e.target as HTMLInputElement).blur();
              }
            }}
          />
          <Button
            onClick={handleSubmit}
            disabled={!queryText.trim()}
            className="rounded-none h-auto bg-gold text-primary-foreground font-mono text-[length:var(--text-chrome)] font-medium tracking-[0.12em] px-3 py-[9px] hover:bg-gold-hover disabled:bg-interactive-ghost disabled:text-muted-foreground disabled:opacity-100"
          >
            QUERY
          </Button>
        </div>
      </div>

      <div className="flex-1 min-h-0 overflow-y-auto" onClick={onContentClick}>
        {children}
      </div>

      {footer}
    </div>
  );
}
