// web/src/lib/components/btw-thread.svelte
<script lang="ts">
  import ChevronDown from "@lucide/svelte/icons/chevron-down";
  import ChevronRight from "@lucide/svelte/icons/chevron-right";
  import { onMount, tick } from "svelte";

  import ArticleBadge from "$lib/components/article-badge.svelte";
  import FilterBadge from "$lib/components/filter-badge.svelte";
  import MarkdownView from "$lib/components/markdown-view.svelte";
  import SearchBadge from "$lib/components/search-badge.svelte";
  import { Button } from "$lib/components/ui/button";
  import * as Collapsible from "$lib/components/ui/collapsible";
  import type { BtwThread } from "$lib/types";

  let {
    btw,
    onReply,
    onDismiss,
    onSpinOff,
  }: {
    btw: BtwThread;
    onReply: (btwId: string, text: string) => void;
    onDismiss?: (btwId: string) => void;
    onSpinOff?: (btwId: string) => void;
  } = $props();

  let input = $state("");
  let open = $state(true);
  let inputElement: HTMLInputElement | null = $state(null);
  const shortAnchor = $derived(
    btw.anchor.quote.length > 58
      ? `${btw.anchor.quote.slice(0, 58)}...`
      : btw.anchor.quote,
  );
  const isStreaming = $derived(
    btw.exchanges.some((exchange) => exchange.streaming),
  );
  let mounted = false;
  let wasStreaming = false;

  onMount(() => {
    mounted = true;
    if (btw.exchanges.length === 0) {
      inputElement?.focus({ preventScroll: true });
    }
  });

  $effect(() => {
    const streaming = isStreaming;
    if (mounted && wasStreaming && !streaming) {
      void tick().then(() => {
        const active = document.activeElement;
        if (active === null || active === document.body) {
          inputElement?.focus({ preventScroll: true });
        }
      });
    }
    wasStreaming = streaming;
  });

  function submit() {
    const text = input.trim();
    if (!text) return;
    onReply(btw.id, text);
    input = "";
  }
</script>

<Collapsible.Root
  bind:open
  class="my-[10px] mb-3 border-l-2 border-gold-dim pl-3.5"
>
  <Collapsible.Trigger>
    {#snippet child({ props })}
      <Button
        {...props}
        variant="ghost"
        class="flex h-auto w-full items-baseline justify-start gap-2 rounded-none p-0 pb-[7px] text-left hover:bg-transparent"
      >
        <span
          class="shrink-0 font-mono text-[length:var(--text-chrome)] tracking-[0.16em] text-gold uppercase"
        >
          BTW
        </span>
        <span
          class="flex-1 text-left text-[length:var(--text-caption)] text-muted-foreground italic"
        >
          “{shortAnchor}”
        </span>
        <span
          class="shrink-0 font-mono text-[length:var(--text-chrome)] text-interactive-dim"
        >
          {#if open}
            <ChevronDown size={10} />
          {:else}
            <ChevronRight size={10} />
          {/if}
        </span>
      </Button>
    {/snippet}
  </Collapsible.Trigger>

  <Collapsible.Content>
    {#each btw.exchanges as exchange (exchange.id)}
      {@const sources = exchange.thinking.flatMap((block) => block.sources)}
      <div>
        <div
          class="mb-[9px] text-[length:var(--text-small)] leading-[1.72] text-warm-ghost italic"
        >
          <span
            class="mr-0.5 font-mono text-[length:var(--text-chrome)] tracking-[0.1em] text-interactive-dim not-italic"
          >
            you ·
          </span>
          {exchange.query}
        </div>

        {#if sources.length > 0}
          <div class="mb-[9px] flex flex-wrap gap-[5px]">
            {#each sources as source, index (`${source.type}:${index}:${source.label}`)}
              {#if source.type === "search"}
                <SearchBadge {source} />
              {:else if source.type === "query"}
                <FilterBadge
                  summary={source.label}
                  pending={source.pending === true}
                />
              {:else}
                <ArticleBadge {source} />
              {/if}
            {/each}
          </div>
        {/if}

        {#if exchange.streaming && !exchange.answer}
          <div
            class="mb-[9px] animate-[pulse-fade_1.6s_ease-in-out_infinite] text-[length:var(--text-small)] leading-[1.72] text-warm-faint"
          >
            {sources.length > 0 ? "reading..." : "thinking..."}
          </div>
        {:else if !exchange.streaming && !exchange.answer}
          <div
            class="mb-[9px] font-mono text-[length:var(--text-chrome)] tracking-[0.06em] text-warm-ghost italic"
          >
            reply interrupted — ask again below
          </div>
        {:else}
          <div
            class="mb-[9px] text-[length:var(--text-small)] leading-[1.72] text-warm-faint"
          >
            <MarkdownView source={exchange.answer} variant="btw" />
            {#if exchange.streaming}
              <span
                class="ml-px inline-block h-2.5 w-px animate-[blink_1s_step-end_infinite] bg-gold-muted align-middle"
              ></span>
            {/if}
          </div>
        {/if}
      </div>
    {/each}

    {#if onSpinOff && btw.exchanges.length > 0 && !isStreaming}
      <div
        class="mb-[6px] text-[length:var(--text-chrome)] tracking-[0.06em] text-interactive-dim italic"
      >
        ephemeral ·
        <button
          type="button"
          onclick={() => onSpinOff?.(btw.id)}
          class="font-mono tracking-[0.1em] text-gold uppercase not-italic transition-colors hover:text-foreground"
        >
          save as session
        </button>
      </div>
    {/if}

    {#if !isStreaming}
      <div
        class="mt-[5px]"
        role="presentation"
        onmousedown={(event) => event.stopPropagation()}
      >
        <input
          bind:this={inputElement}
          bind:value={input}
          class="w-full border-0 border-b border-b-gold-dim bg-transparent py-[3px] font-serif text-[length:var(--text-caption)] text-warm-ghost italic caret-gold outline-none transition-colors placeholder:text-interactive-dim focus:border-b-gold"
          placeholder="continue..."
          onblur={() => {
            if (btw.exchanges.length === 0 && !input.trim() && onDismiss) {
              onDismiss(btw.id);
            }
          }}
          onkeydown={(event) => {
            if (event.key === "Enter") submit();
          }}
        />
      </div>
    {/if}
  </Collapsible.Content>
</Collapsible.Root>

// web/src/components/btw-thread.tsx
import { memo, useEffect, useRef, useState } from "react";
import Markdown from "react-markdown";
import { ChevronDown, ChevronRight, Waypoints } from "lucide-react";

import { Button } from "@/components/ui/button";
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/components/ui/collapsible";
import { ArticleBadge, FilterBadge, SearchBadge } from "@/components/thinking-section";
import { baseMdComponents, remarkPlugins, rehypePlugins } from "@/lib/markdown";
import type { BtwThread as BtwThreadType } from "@/lib/types";

interface BtwThreadProps {
  btw: BtwThreadType;
  onReply: (btwId: string, text: string) => void;
  onDismiss?: (btwId: string) => void;
  // When provided, this BTW is ephemeral and offers a "save as session" action.
  // Session-attached BTWs (which auto-persist) leave this undefined.
  onSpinOff?: (btwId: string) => void;
}

const btwMdComponents = {
  ...baseMdComponents,
  p: ({ children }: { children?: React.ReactNode }) => <p className="mb-2 last:mb-0">{children}</p>,
  ul: ({ children }: { children?: React.ReactNode }) => (
    <ul className="list-disc list-inside mb-1 ml-2">{children}</ul>
  ),
  ol: ({ children }: { children?: React.ReactNode }) => (
    <ol className="list-decimal list-inside mb-1 ml-2">{children}</ol>
  ),
  blockquote: ({ children }: { children?: React.ReactNode }) => (
    <blockquote className="border-l-2 border-gold-dim pl-2.5 text-warm-faint italic my-1.5">
      {children}
    </blockquote>
  ),
  code: ({ children }: { children?: React.ReactNode }) => (
    <code className="font-mono text-[length:var(--text-chrome)] bg-code-bg px-1 py-0.5 rounded-sm text-gold">
      {children}
    </code>
  ),
};

export const BtwThread = memo(function BtwThread({
  btw,
  onReply,
  onDismiss,
  onSpinOff,
}: BtwThreadProps) {
  const [input, setInput] = useState("");
  const [open, setOpen] = useState(true);
  const inputRef = useRef<HTMLInputElement>(null);

  const quote = btw.anchor.quote;
  const shortAnchor = quote.length > 58 ? quote.slice(0, 58) + "..." : quote;
  const isStreaming = btw.exchanges.some((e) => e.streaming);

  // Auto-focus: on mount of a brand-new (empty) BTW, and when this thread's
  // streaming finishes — but never steal focus from something the user is
  // typing in, and never scroll-jump the page to reach the input.
  const wasStreaming = useRef(isStreaming);
  const isFirstRender = useRef(true);
  useEffect(() => {
    const idleFocus = () => {
      const active = document.activeElement;
      if (active === null || active === document.body) {
        inputRef.current?.focus({ preventScroll: true });
      }
    };
    if (isFirstRender.current) {
      isFirstRender.current = false;
      if (btw.exchanges.length === 0) {
        inputRef.current?.focus({ preventScroll: true });
      }
      return;
    }
    if (wasStreaming.current && !isStreaming) {
      idleFocus();
    }
    wasStreaming.current = isStreaming;
  }, [isStreaming, btw.exchanges.length]);

  return (
    <Collapsible
      open={open}
      onOpenChange={setOpen}
      className="my-[10px] mb-3 border-l-2 border-gold-dim pl-3.5"
    >
      <CollapsibleTrigger
        render={
          <Button
            variant="ghost"
            className="flex items-baseline gap-2 w-full pb-[7px] text-left h-auto p-0 rounded-none hover:bg-transparent justify-start"
          />
        }
      >
        <span className="font-mono text-[length:var(--text-chrome)] tracking-[0.16em] text-gold uppercase shrink-0">
          BTW
        </span>
        <span className="italic text-[length:var(--text-caption)] text-muted-foreground flex-1 text-left">
          {`"${shortAnchor}"`}
        </span>
        <span className="font-mono text-[length:var(--text-chrome)] text-interactive-dim shrink-0">
          {open ? <ChevronDown size={10} /> : <ChevronRight size={10} />}
        </span>
      </CollapsibleTrigger>

      <CollapsibleContent>
        {btw.exchanges.map((ex) => {
          const sources = ex.thinking.flatMap((block) => block.sources);
          return (
            <div key={ex.id}>
              <div className="text-[length:var(--text-small)] leading-[1.72] mb-[9px] text-warm-ghost italic">
                <span className="font-mono not-italic text-[length:var(--text-chrome)] tracking-[0.1em] text-interactive-dim mr-0.5">
                  you ·{" "}
                </span>
                {ex.query}
              </div>
              {sources.length > 0 && (
                <div className="flex flex-wrap gap-[5px] mb-[9px]">
                  {sources.map((s, si) => {
                    if (s.type === "search") return <SearchBadge key={si} source={s} />;
                    if (s.type === "query") return <FilterBadge key={si} summary={s.label} />;
                    return (
                      <ArticleBadge
                        key={si}
                        label={s.label}
                        title={s.title}
                        thinking={s.thinking ?? undefined}
                        active={false}
                        icon={
                          s.type === "links" ? (
                            <Waypoints size={9} className="mr-1.5 opacity-60" />
                          ) : undefined
                        }
                      />
                    );
                  })}
                </div>
              )}
              {ex.streaming && !ex.answer ? (
                <div className="text-[length:var(--text-small)] leading-[1.72] mb-[9px] text-warm-faint animate-[pulse-fade_1.6s_ease-in-out_infinite]">
                  {sources.length > 0 ? "reading..." : "thinking..."}
                </div>
              ) : (
                <div className="text-[length:var(--text-small)] leading-[1.72] mb-[9px] text-warm-faint">
                  <Markdown
                    remarkPlugins={remarkPlugins}
                    rehypePlugins={rehypePlugins}
                    components={btwMdComponents}
                  >
                    {ex.answer}
                  </Markdown>
                  {ex.streaming && (
                    <span className="inline-block w-px h-2.5 bg-gold-muted animate-[blink_1s_step-end_infinite] align-middle ml-px" />
                  )}
                </div>
              )}
            </div>
          );
        })}

        {onSpinOff && btw.exchanges.length > 0 && !isStreaming && (
          <div className="text-[length:var(--text-chrome)] tracking-[0.06em] text-interactive-dim italic mb-[6px]">
            ephemeral ·{" "}
            <button
              type="button"
              onClick={() => onSpinOff(btw.id)}
              className="not-italic font-mono tracking-[0.1em] uppercase text-gold hover:text-foreground transition-colors"
            >
              save as session
            </button>
          </div>
        )}

        {!isStreaming && (
          <div className="mt-[5px]" onMouseDown={(e) => e.stopPropagation()}>
            <input
              ref={inputRef}
              className="bg-transparent border-0 border-b border-b-gold-dim outline-none text-warm-ghost font-serif italic text-[length:var(--text-caption)] py-[3px] w-full caret-gold placeholder:text-interactive-dim focus:border-b-gold transition-colors"
              placeholder="continue..."
              value={input}
              onChange={(e) => setInput(e.target.value)}
              onBlur={() => {
                if (btw.exchanges.length === 0 && !input.trim() && onDismiss) {
                  onDismiss(btw.id);
                }
              }}
              onKeyDown={(e) => {
                if (e.key === "Enter" && input.trim()) {
                  onReply(btw.id, input.trim());
                  setInput("");
                }
              }}
            />
          </div>
        )}
      </CollapsibleContent>
    </Collapsible>
  );
});
