// web/src/lib/components/corner-menu.svelte
<script lang="ts">
  import LogOut from "@lucide/svelte/icons/log-out";
  import Moon from "@lucide/svelte/icons/moon";
  import Settings from "@lucide/svelte/icons/settings";
  import Sun from "@lucide/svelte/icons/sun";

  import { auth } from "$lib/auth.svelte";
  import { Button } from "$lib/components/ui/button";
  import * as DropdownMenu from "$lib/components/ui/dropdown-menu";
  import { MENU_ITEM_CLASS, POPOVER_SURFACE_CLASS } from "$lib/control-styles";
  import { theme } from "$lib/theme.svelte";
</script>

{#if auth.isAuthenticated}
  <DropdownMenu.Root>
    <DropdownMenu.Trigger>
      {#snippet child({ props })}
        <Button
          {...props}
          variant="ghost"
          size="icon-sm"
          aria-label="settings"
          class="rounded-sm text-warm-ghost hover:bg-ink-raised hover:text-warm-faint"
        >
          <Settings class="size-4" />
        </Button>
      {/snippet}
    </DropdownMenu.Trigger>
    <DropdownMenu.Content
      side="top"
      align="start"
      sideOffset={8}
      class={`w-auto min-w-0 p-1 ${POPOVER_SURFACE_CLASS}`}
    >
      <DropdownMenu.Item
        onclick={() => theme.toggle()}
        class={`${MENU_ITEM_CLASS} cursor-pointer gap-2`}
      >
        {#if theme.current === "dark"}
          <Sun class="size-3.5" />
          light mode
        {:else}
          <Moon class="size-3.5" />
          dark mode
        {/if}
      </DropdownMenu.Item>
      <DropdownMenu.Item
        onclick={() => auth.logout()}
        class={`${MENU_ITEM_CLASS} cursor-pointer gap-2`}
      >
        <LogOut class="size-3.5" />
        sign out
      </DropdownMenu.Item>
    </DropdownMenu.Content>
  </DropdownMenu.Root>
{/if}

// web/src/components/corner-menu.tsx
import { LogOut, Moon, Settings, Sun } from "lucide-react";

import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { MENU_ITEM_CLASS, POPOVER_SURFACE_CLASS } from "@/lib/control-styles";

interface CornerMenuProps {
  theme: "light" | "dark";
  onToggleTheme: () => void;
  onSignOut?: () => void;
}

export function CornerMenu({ theme, onToggleTheme, onSignOut }: CornerMenuProps) {
  return (
    <DropdownMenu>
      <DropdownMenuTrigger
        render={
          <Button
            variant="ghost"
            size="icon-sm"
            aria-label="settings"
            className="text-warm-ghost hover:text-warm-faint hover:bg-ink-raised rounded-sm"
          />
        }
      >
        <Settings className="size-4" />
      </DropdownMenuTrigger>
      <DropdownMenuContent
        side="top"
        align="start"
        sideOffset={8}
        className={`w-auto min-w-0 p-1 ${POPOVER_SURFACE_CLASS}`}
      >
        <DropdownMenuItem
          onClick={onToggleTheme}
          className={`${MENU_ITEM_CLASS} gap-2 cursor-pointer`}
        >
          {theme === "dark" ? <Sun className="size-3.5" /> : <Moon className="size-3.5" />}
          {theme === "dark" ? "light mode" : "dark mode"}
        </DropdownMenuItem>
        {onSignOut ? (
          <DropdownMenuItem
            onClick={onSignOut}
            className={`${MENU_ITEM_CLASS} gap-2 cursor-pointer`}
          >
            <LogOut className="size-3.5" />
            sign out
          </DropdownMenuItem>
        ) : null}
      </DropdownMenuContent>
    </DropdownMenu>
  );
}
