// web/src/lib/components/login-form.svelte
<script lang="ts">
  import { goto } from "$app/navigation";

  import { loginWithCode, requestCode } from "$lib/api/client";
  import { auth } from "$lib/auth.svelte";
  import { Alert, AlertDescription } from "$lib/components/ui/alert";
  import { Label } from "$lib/components/ui/label";

  type Step = "email" | "code";

  let step = $state<Step>("email");
  let email = $state("");
  let code = $state("");
  let error = $state("");
  let loading = $state(false);

  async function handleRequestCode(event: SubmitEvent): Promise<void> {
    event.preventDefault();
    error = "";
    loading = true;
    try {
      await requestCode(email);
      if (import.meta.env.VITE_SUPPRESS_AUTH) {
        await loginWithCode(email, "000000");
        auth.login();
        await goto("/");
      } else {
        step = "code";
      }
    } catch {
      error = "Failed to send code. Check your email and try again.";
    } finally {
      loading = false;
    }
  }

  async function handleVerifyCode(event: SubmitEvent): Promise<void> {
    event.preventDefault();
    error = "";
    loading = true;
    try {
      await loginWithCode(email, code);
      auth.login();
      await goto("/");
    } catch {
      error = "Invalid or expired code.";
    } finally {
      loading = false;
    }
  }

  function handleBack(): void {
    step = "email";
    code = "";
    error = "";
  }
</script>

<div class="flex h-screen items-center justify-center bg-ink">
  <div class="w-full max-w-sm space-y-8 px-6">
    <div class="text-center">
      <h1 class="font-serif text-title text-warm">Great Minds</h1>
      <p class="mt-2 text-small text-warm-faint">
        {step === "email"
          ? "Enter your email to sign in"
          : `Code sent to ${email}`}
      </p>
    </div>

    {#if error}
      <Alert
        variant="destructive"
        class="rounded-sm border-red-400/25 bg-red-400/5"
      >
        <AlertDescription class="text-center text-small text-red-400/90">
          {error}
        </AlertDescription>
      </Alert>
    {/if}

    {#if step === "email"}
      <form onsubmit={handleRequestCode} class="space-y-4">
        <Label for="login-email" class="sr-only">Email address</Label>
        <!-- svelte-ignore a11y_autofocus -->
        <input
          id="login-email"
          type="email"
          bind:value={email}
          placeholder="you@example.com"
          required
          autofocus
          class="w-full rounded-sm border border-ink-border bg-ink-raised px-4 py-3 font-mono text-small text-warm placeholder:text-warm-ghost outline-none focus:border-gold-dim"
        />
        <button
          type="submit"
          disabled={loading}
          class="w-full rounded-sm bg-gold px-4 py-3 font-mono text-small text-primary-foreground font-semibold hover:bg-gold-hover disabled:opacity-50 transition-colors"
        >
          {loading ? "Sending..." : "Send code"}
        </button>
      </form>
    {:else}
      <form onsubmit={handleVerifyCode} class="space-y-4">
        <Label for="login-code" class="sr-only">Verification code</Label>
        <!-- svelte-ignore a11y_autofocus -->
        <input
          id="login-code"
          type="text"
          bind:value={code}
          placeholder="6-digit code"
          required
          autofocus
          maxlength={6}
          inputmode="numeric"
          pattern="[0-9]*"
          class="w-full rounded-sm border border-ink-border bg-ink-raised px-4 py-3 font-mono text-small text-warm text-center tracking-[0.5em] placeholder:tracking-normal placeholder:text-warm-ghost outline-none focus:border-gold-dim"
        />
        <button
          type="submit"
          disabled={loading}
          class="w-full rounded-sm bg-gold px-4 py-3 font-mono text-small text-primary-foreground font-semibold hover:bg-gold-hover disabled:opacity-50 transition-colors"
        >
          {loading ? "Verifying..." : "Sign in"}
        </button>
        <button
          type="button"
          onclick={handleBack}
          class="w-full text-center text-caption text-warm-faint hover:text-warm transition-colors"
        >
          Use a different email
        </button>
      </form>
    {/if}
  </div>
</div>

// web/src/components/login-form.tsx
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Label } from "@/components/ui/label";

interface LoginFormProps {
  step: "email" | "code";
  email: string;
  code: string;
  error: string;
  loading: boolean;
  onEmailChange: (value: string) => void;
  onCodeChange: (value: string) => void;
  onRequestCode: (e: React.FormEvent) => void;
  onVerifyCode: (e: React.FormEvent) => void;
  onBack: () => void;
}

export default function LoginForm({
  step,
  email,
  code,
  error,
  loading,
  onEmailChange,
  onCodeChange,
  onRequestCode,
  onVerifyCode,
  onBack,
}: LoginFormProps) {
  return (
    <div className="flex h-screen items-center justify-center bg-ink">
      <div className="w-full max-w-sm space-y-8 px-6">
        <div className="text-center">
          <h1 className="font-serif text-title text-warm">Great Minds</h1>
          <p className="mt-2 text-small text-warm-faint">
            {step === "email" ? "Enter your email to sign in" : `Code sent to ${email}`}
          </p>
        </div>

        {error && (
          <Alert variant="destructive" className="rounded-sm border-red-400/25 bg-red-400/5">
            <AlertDescription className="text-center text-small text-red-400/90">
              {error}
            </AlertDescription>
          </Alert>
        )}

        {step === "email" ? (
          <form onSubmit={onRequestCode} className="space-y-4">
            <Label htmlFor="login-email" className="sr-only">
              Email address
            </Label>
            <input
              id="login-email"
              type="email"
              value={email}
              onChange={(e) => onEmailChange(e.target.value)}
              placeholder="you@example.com"
              required
              autoFocus
              className="w-full rounded-sm border border-ink-border bg-ink-raised px-4 py-3 font-mono text-small text-warm placeholder:text-warm-ghost outline-none focus:border-gold-dim"
            />
            <button
              type="submit"
              disabled={loading}
              className="w-full rounded-sm bg-gold px-4 py-3 font-mono text-small text-primary-foreground font-semibold hover:bg-gold-hover disabled:opacity-50 transition-colors"
            >
              {loading ? "Sending..." : "Send code"}
            </button>
          </form>
        ) : (
          <form onSubmit={onVerifyCode} className="space-y-4">
            <Label htmlFor="login-code" className="sr-only">
              Verification code
            </Label>
            <input
              id="login-code"
              type="text"
              value={code}
              onChange={(e) => onCodeChange(e.target.value)}
              placeholder="6-digit code"
              required
              autoFocus
              maxLength={6}
              inputMode="numeric"
              pattern="[0-9]*"
              className="w-full rounded-sm border border-ink-border bg-ink-raised px-4 py-3 font-mono text-small text-warm text-center tracking-[0.5em] placeholder:tracking-normal placeholder:text-warm-ghost outline-none focus:border-gold-dim"
            />
            <button
              type="submit"
              disabled={loading}
              className="w-full rounded-sm bg-gold px-4 py-3 font-mono text-small text-primary-foreground font-semibold hover:bg-gold-hover disabled:opacity-50 transition-colors"
            >
              {loading ? "Verifying..." : "Sign in"}
            </button>
            <button
              type="button"
              onClick={onBack}
              className="w-full text-center text-caption text-warm-faint hover:text-warm transition-colors"
            >
              Use a different email
            </button>
          </form>
        )}
      </div>
    </div>
  );
}
