// web/src/components/app-shell.tsx
import type { ReactNode } from "react";

interface AppShellProps {
  utility?: ReactNode;
  children: ReactNode;
}

export function AppShell({ utility, children }: AppShellProps) {
  return (
    <div
      className="relative h-screen"
      style={{ "--shell-utility-inset": utility ? "3.5rem" : "2.5rem" } as React.CSSProperties}
    >
      {children}
      {utility && <div className="fixed bottom-4 left-4 z-[100]">{utility}</div>}
    </div>
  );
}

// web/src/lib/components/app-shell.svelte
<script lang="ts">
  import type { Snippet } from "svelte";

  let {
    children,
    utility,
  }: {
    children: Snippet;
    utility?: Snippet;
  } = $props();
</script>

<div
  class="relative h-screen"
  style:--shell-utility-inset={utility ? "3.5rem" : "2.5rem"}
>
  {@render children()}
  {#if utility}
    <div class="fixed bottom-4 left-4 z-[100]">
      {@render utility()}
    </div>
  {/if}
</div>
