// web/src/components/doc-header.tsx
import { ChevronDown, ChevronRight, ExternalLink } from "lucide-react";
import { useState } from "react";

import { Button } from "@/components/ui/button";
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/components/ui/collapsible";
import { articleMeta, type Article } from "@/api/doc";
import { CHIP_BASE, CHIP_INACTIVE } from "@/lib/chip";
import { cn } from "@/lib/utils";

interface DocHeaderProps {
  document: Article;
  archived?: boolean;
  supersededBy?: string | null;
  onSupersessorClick?: (slug: string) => void;
}

/**
 * Chrome block above the document body: title, subtitle, metadata
 * row, tag chips, origin link, and a collapsed "more metadata" panel
 * for per-vault custom fields that don't have a dedicated slot.
 *
 * Works for both wiki and raw documents — missing fields (e.g. author
 * on a wiki doc, description on a raw doc) render nothing.
 */
export function DocHeader({
  document,
  archived = false,
  supersededBy = null,
  onSupersessorClick,
}: DocHeaderProps) {
  const [extraOpen, setExtraOpen] = useState(false);
  const metadata = articleMeta(document);

  const metaParts: string[] = [];
  if (metadata.author) metaParts.push(metadata.author);
  if (metadata.published_date) metaParts.push(metadata.published_date);
  if (metadata.genre) metaParts.push(metadata.genre);

  const extraEntries = Object.entries(metadata.derived_extras ?? {}).filter(
    ([k]) => k !== "topic_id", // internal identifier, not for display
  );

  return (
    <header className="mb-10">
      {archived && (
        <div className="mb-6 px-4 py-3 rounded-sm border border-gold-dim bg-ink-raised">
          <p className="font-mono text-[length:var(--text-chrome)] tracking-[0.08em] text-gold-muted uppercase mb-1">
            archived article
          </p>
          <p className="font-serif text-[length:var(--text-body)] text-warm-dim">
            {supersededBy ? (
              <>
                This concept has been retired. See{" "}
                <button
                  type="button"
                  onClick={() => onSupersessorClick?.(supersededBy)}
                  className="text-gold hover:text-gold-bright underline underline-offset-2"
                >
                  {supersededBy}
                </button>{" "}
                for the current version.
              </>
            ) : (
              <>This concept has been retired. No successor has been identified.</>
            )}
          </p>
        </div>
      )}

      <h1 className="text-[length:var(--text-title)] font-bold text-foreground mb-3">
        {metadata.title}
      </h1>

      {metadata.precis && (
        <p className="font-serif text-[length:var(--text-body)] text-warm-dim italic leading-[1.6] mb-4">
          {metadata.precis}
        </p>
      )}

      {metaParts.length > 0 && (
        <p className="font-mono text-[length:var(--text-chrome)] tracking-[0.06em] text-warm-faint mb-3">
          {metaParts.join(" · ")}
        </p>
      )}

      {metadata.tags.length > 0 && (
        <div className="flex flex-wrap gap-2 mb-3">
          {metadata.tags.map((tag) => (
            <span key={tag} className={cn(CHIP_BASE, CHIP_INACTIVE)}>
              {tag}
            </span>
          ))}
        </div>
      )}

      {(metadata.url || metadata.origin) && (
        <p className="font-mono text-[length:var(--text-chrome)] tracking-[0.06em] text-warm-ghost mb-3">
          {metadata.url ? (
            <a
              href={metadata.url}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-1 text-gold-muted hover:text-gold underline underline-offset-2 decoration-gold/30"
            >
              from {metadata.origin || metadata.url}
              <ExternalLink size={11} />
            </a>
          ) : (
            <>from {metadata.origin}</>
          )}
        </p>
      )}

      {extraEntries.length > 0 && (
        <Collapsible open={extraOpen} onOpenChange={setExtraOpen} className="mt-4">
          <CollapsibleTrigger
            render={
              <Button
                variant="ghost"
                className="flex items-center gap-2 h-auto p-0 rounded-none hover:bg-transparent font-mono text-[length:var(--text-chrome)] tracking-[0.08em] text-warm-ghost hover:text-warm-faint uppercase"
              />
            }
          >
            {extraOpen ? <ChevronDown size={11} /> : <ChevronRight size={11} />}
            more metadata
          </CollapsibleTrigger>
          <CollapsibleContent>
            <dl className="mt-3 grid grid-cols-[max-content_1fr] gap-x-4 gap-y-1.5 font-mono text-[length:var(--text-chrome)] text-warm-ghost">
              {extraEntries.map(([k, v]) => (
                <ExtraRow key={k} name={k} value={v} />
              ))}
            </dl>
          </CollapsibleContent>
        </Collapsible>
      )}
    </header>
  );
}

function ExtraRow({ name, value }: { name: string; value: unknown }) {
  return (
    <>
      <dt className="text-gold-muted tracking-[0.08em]">{name}</dt>
      <dd className="text-warm-faint">{formatValue(value)}</dd>
    </>
  );
}

function formatValue(value: unknown): string {
  if (value === null || value === undefined) return "—";
  if (Array.isArray(value)) return value.length ? value.join(", ") : "—";
  if (typeof value === "object") return JSON.stringify(value);
  return String(value);
}

// web/src/lib/components/doc-header.svelte
<script lang="ts">
  import ChevronDown from "@lucide/svelte/icons/chevron-down";
  import ChevronRight from "@lucide/svelte/icons/chevron-right";
  import ExternalLink from "@lucide/svelte/icons/external-link";

  import { articleMeta, type Article } from "$lib/api/doc";
  import * as Collapsible from "$lib/components/ui/collapsible";
  import { CHIP_BASE, CHIP_INACTIVE } from "$lib/chip";
  import { cn } from "$lib/utils";

  let {
    document,
    archived = false,
    supersededBy = null,
    onSupersessorClick,
  }: {
    document: Article;
    archived?: boolean;
    supersededBy?: string | null;
    onSupersessorClick?: (slug: string) => void;
  } = $props();

  let extraOpen = $state(false);
  const metadata = $derived(articleMeta(document));
  const metaParts = $derived(
    [metadata.author, metadata.published_date, metadata.genre].filter(
      (part): part is string => !!part,
    ),
  );
  const extraEntries = $derived(
    Object.entries(metadata.derived_extras ?? {}).filter(
      ([key]) => key !== "topic_id",
    ),
  );

  function formatValue(value: unknown): string {
    if (value === null || value === undefined) return "—";
    if (Array.isArray(value)) return value.length ? value.join(", ") : "—";
    if (typeof value === "object") return JSON.stringify(value);
    return String(value);
  }
</script>

<header class="mb-10">
  {#if archived}
    <div class="mb-6 rounded-sm border border-gold-dim bg-ink-raised px-4 py-3">
      <p
        class="mb-1 font-mono text-[length:var(--text-chrome)] tracking-[0.08em] text-gold-muted uppercase"
      >
        archived article
      </p>
      <p class="font-serif text-[length:var(--text-body)] text-warm-dim">
        {#if supersededBy}
          This concept has been retired. See
          <button
            type="button"
            onclick={() => onSupersessorClick?.(supersededBy)}
            class="text-gold underline underline-offset-2 hover:text-gold-bright"
          >
            {supersededBy}
          </button>
          for the current version.
        {:else}
          This concept has been retired. No successor has been identified.
        {/if}
      </p>
    </div>
  {/if}

  <h1 class="mb-3 text-[length:var(--text-title)] font-bold text-foreground">
    {metadata.title}
  </h1>

  {#if metadata.precis}
    <p
      class="mb-4 font-serif text-[length:var(--text-body)] leading-[1.6] text-warm-dim italic"
    >
      {metadata.precis}
    </p>
  {/if}

  {#if metaParts.length > 0}
    <p
      class="mb-3 font-mono text-[length:var(--text-chrome)] tracking-[0.06em] text-warm-faint"
    >
      {metaParts.join(" · ")}
    </p>
  {/if}

  {#if metadata.tags.length > 0}
    <div class="mb-3 flex flex-wrap gap-2">
      {#each metadata.tags as tag (tag)}
        <span class={cn(CHIP_BASE, CHIP_INACTIVE)}>{tag}</span>
      {/each}
    </div>
  {/if}

  {#if metadata.url || metadata.origin}
    <p
      class="mb-3 font-mono text-[length:var(--text-chrome)] tracking-[0.06em] text-warm-ghost"
    >
      {#if metadata.url}
        <a
          href={metadata.url}
          target="_blank"
          rel="noopener noreferrer"
          class="inline-flex items-center gap-1 text-gold-muted underline decoration-gold/30 underline-offset-2 hover:text-gold"
        >
          from {metadata.origin || metadata.url}
          <ExternalLink size={11} />
        </a>
      {:else}
        from {metadata.origin}
      {/if}
    </p>
  {/if}

  {#if extraEntries.length > 0}
    <Collapsible.Root bind:open={extraOpen} class="mt-4">
      <Collapsible.Trigger
        class="flex h-auto items-center gap-2 rounded-none p-0 font-mono text-[length:var(--text-chrome)] tracking-[0.08em] text-warm-ghost uppercase hover:bg-transparent hover:text-warm-faint"
      >
        {#if extraOpen}
          <ChevronDown size={11} />
        {:else}
          <ChevronRight size={11} />
        {/if}
        more metadata
      </Collapsible.Trigger>
      <Collapsible.Content>
        <dl
          class="mt-3 grid grid-cols-[max-content_1fr] gap-x-4 gap-y-1.5 font-mono text-[length:var(--text-chrome)] text-warm-ghost"
        >
          {#each extraEntries as [name, value] (name)}
            <dt class="tracking-[0.08em] text-gold-muted">{name}</dt>
            <dd class="break-words text-warm-faint">{formatValue(value)}</dd>
          {/each}
        </dl>
      </Collapsible.Content>
    </Collapsible.Root>
  {/if}
</header>
