// web/src/components/ingestion-flow.tsx
import { useCallback, useEffect, useRef, useState } from "react";
import { motion, useReducedMotion } from "motion/react";

import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { ScrollArea } from "@/components/ui/scroll-area";
import { checkDupes, hashFile, type HashedFile } from "@/api/ingest";
import { useViewNavigate } from "@/hooks/use-view-navigate";
import type { DroppedFile } from "@/lib/types";

const LAYOUT_ID = "ingestion-zone";

/** Extensions MarkItDown can convert. Unrecognised types get a warning
 *  but aren't blocked — the backend may handle types we don't list. */
const RECOGNISED_EXTS = new Set([
  ".md",
  ".markdown",
  ".txt",
  ".text",
  ".pdf",
  ".docx",
  ".doc",
  ".pptx",
  ".ppt",
  ".xlsx",
  ".xls",
  ".csv",
  ".json",
  ".xml",
  ".html",
  ".htm",
  ".epub",
  ".rtf",
  ".odt",
]);

const HASH_CONCURRENCY = 4;

/** Per-file lifecycle in the ingestion preview. */
type FileStatus =
  | "checking" // hash in progress
  | "unique" // fresh content, included by default
  | "duplicate-in-batch" // another selected file has the same hash
  | "duplicate-in-vault" // hash already in this vault
  | "unrecognised" // extension not in RECOGNISED_EXTS
  | "error"; // couldn't read or hash

interface IngestableFile {
  id: string;
  file: File;
  path: string;
  ext: string;
  status: FileStatus;
  hash?: string;
  selected: boolean;
  error?: string;
}

function formatSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

function extOf(name: string): string {
  return name.includes(".") ? `.${name.split(".").pop()?.toLowerCase()}` : "";
}

async function filesFromDrop(dataTransfer: DataTransfer): Promise<DroppedFile[]> {
  const items = Array.from(dataTransfer.items);
  const entries = items
    .map((item) => item.webkitGetAsEntry?.())
    .filter((e): e is FileSystemEntry => e != null);

  if (entries.length > 0) {
    return collectAll(entries, "");
  }
  return Array.from(dataTransfer.files).map((f) => ({ file: f, path: f.name }));
}

async function collectAll(entries: FileSystemEntry[], prefix: string): Promise<DroppedFile[]> {
  const results: DroppedFile[] = [];
  for (const entry of entries) {
    if (entry.isFile) {
      const fileEntry = entry as FileSystemFileEntry;
      const file = await new Promise<File>((resolve, reject) => fileEntry.file(resolve, reject));
      results.push({
        file,
        path: prefix ? `${prefix}/${entry.name}` : entry.name,
      });
    } else if (entry.isDirectory) {
      const dirEntry = entry as FileSystemDirectoryEntry;
      const reader = dirEntry.createReader();
      const children: FileSystemEntry[] = [];
      let batch: FileSystemEntry[];
      do {
        batch = await new Promise((resolve) => reader.readEntries((e) => resolve(e)));
        children.push(...batch);
      } while (batch.length > 0);
      const dir = prefix ? `${prefix}/${entry.name}` : entry.name;
      const nested = await collectAll(children, dir);
      results.push(...nested);
    }
  }
  return results;
}

function initialIngestable(dropped: DroppedFile[]): IngestableFile[] {
  return dropped.map((d) => {
    const ext = extOf(d.file.name);
    const recognised = ext === "" || RECOGNISED_EXTS.has(ext);
    return {
      id: crypto.randomUUID(),
      file: d.file,
      path: d.path,
      ext,
      // Start unrecognised files in their terminal state — they don't
      // get a vault check. Everything else starts in checking.
      status: recognised ? "checking" : "unrecognised",
      selected: true,
      // Unrecognised files still upload (backend may handle them);
      // they just don't participate in dupe detection.
    };
  });
}

export function IngestionFlow({ hasActivePipeline }: { hasActivePipeline: boolean }) {
  const [expanded, setExpanded] = useState(false);
  const [isDragOver, setDragOver] = useState(false);
  const [url, setUrl] = useState("");
  const [files, setFiles] = useState<IngestableFile[]>([]);
  const dragCounter = useRef(0);
  const hashRunIdRef = useRef(0);
  const zoneRef = useRef<HTMLDivElement>(null);
  const navigate = useViewNavigate();
  const prefersReducedMotion = useReducedMotion();
  const shouldAnimate = !prefersReducedMotion;

  // ---- Actions ----

  const close = useCallback(() => {
    setExpanded(false);
    setFiles([]);
    hashRunIdRef.current += 1; // cancel any in-flight hashing run
    setUrl("");
  }, []);

  // ---- Side-effect: close on click-outside / Escape ----

  useEffect(() => {
    if (!expanded) return;
    const handler = (e: MouseEvent) => {
      if (zoneRef.current && !zoneRef.current.contains(e.target as Node)) {
        close();
      }
    };
    const t = setTimeout(() => document.addEventListener("mousedown", handler), 0);
    return () => {
      clearTimeout(t);
      document.removeEventListener("mousedown", handler);
    };
  }, [expanded, close]);

  useEffect(() => {
    if (!expanded) return;
    const handler = (e: KeyboardEvent) => {
      if (e.key === "Escape") close();
    };
    window.addEventListener("keydown", handler);
    return () => window.removeEventListener("keydown", handler);
  }, [expanded, close]);

  // ---- Side-effect: document-level drag triggers expansion ----

  useEffect(() => {
    let dragDepth = 0;
    const onDragEnter = (e: DragEvent) => {
      e.preventDefault();
      dragDepth += 1;
      if (dragDepth > 0 && !expanded) setExpanded(true);
    };
    const onDragLeave = (e: DragEvent) => {
      e.preventDefault();
      dragDepth = Math.max(0, dragDepth - 1);
    };
    const onDragOver = (e: DragEvent) => e.preventDefault();
    const onDrop = (e: DragEvent) => {
      e.preventDefault();
      dragDepth = 0;
    };

    document.addEventListener("dragenter", onDragEnter);
    document.addEventListener("dragleave", onDragLeave);
    document.addEventListener("dragover", onDragOver);
    document.addEventListener("drop", onDrop);

    return () => {
      document.removeEventListener("dragenter", onDragEnter);
      document.removeEventListener("dragleave", onDragLeave);
      document.removeEventListener("dragover", onDragOver);
      document.removeEventListener("drop", onDrop);
    };
  }, [expanded]);

  // ---- Hashing pipeline ----
  //
  // Each picked batch increments hashRunIdRef. In-flight workers check
  // the run id before applying their result, so a fresh pick (or
  // close) cancels stale updates.

  const runHashingPipeline = useCallback(async (initial: IngestableFile[]) => {
    hashRunIdRef.current += 1;
    const runId = hashRunIdRef.current;

    // Concurrent hashing — yields per-file updates as each completes.
    let cursor = 0;
    async function worker() {
      while (true) {
        const i = cursor++;
        if (i >= initial.length) return;
        const item = initial[i];
        if (item.status !== "checking") continue;
        try {
          const hash = await hashFile(item.file);
          if (hashRunIdRef.current !== runId) return;
          setFiles((prev) => applyHash(prev, item.id, hash));
        } catch (e) {
          if (hashRunIdRef.current !== runId) return;
          const message = e instanceof Error ? e.message : "hash failed";
          setFiles((prev) =>
            prev.map((f) => (f.id === item.id ? { ...f, status: "error", error: message } : f)),
          );
        }
      }
    }
    const workers = Array.from({ length: Math.min(HASH_CONCURRENCY, initial.length) }, worker);
    await Promise.all(workers);
    if (hashRunIdRef.current !== runId) return;

    // Once everyone's hashed, ask the server which already exist.
    const hashes = initial
      .filter((f) => f.status === "checking")
      .map((f) => f.hash)
      .filter((h): h is string => !!h);
    // Some hashes were populated by the setFiles updates above; the
    // initial array still has the snapshot, so use latest state via a
    // setFiles read-then-write. Simpler: read from current state.
    setFiles((current) => {
      const hashList = current
        .filter((f) => f.status === "unique" || f.status === "duplicate-in-batch")
        .map((f) => f.hash!)
        .filter((h) => !!h);
      // Kick off the server check; soft-fail keeps the UI usable
      // even if the endpoint is unreachable.
      void (async () => {
        const existing = await checkDupes(Array.from(new Set(hashList)));
        if (hashRunIdRef.current !== runId) return;
        if (existing.size === 0) return;
        setFiles((prev) =>
          prev.map((f) =>
            f.hash && existing.has(f.hash)
              ? { ...f, status: "duplicate-in-vault", selected: false }
              : f,
          ),
        );
      })();
      return current;
    });
    void hashes; // referenced to keep the compiler quiet about the unused intermediate
  }, []);

  /** Update one file in the list with its computed hash, deriving the
   *  intra-batch dup status against the rest of the list. */
  function applyHash(prev: IngestableFile[], id: string, hash: string): IngestableFile[] {
    const matchesElsewhere = prev.some((f) => f.id !== id && f.hash === hash);
    return prev.map((f) => {
      if (f.id === id) {
        return {
          ...f,
          hash,
          status: matchesElsewhere ? "duplicate-in-batch" : "unique",
          selected: !matchesElsewhere,
        };
      }
      // If this hash already existed on another row, the existing one
      // keeps its status (the FIRST occurrence is "unique"). The new
      // arrival is the duplicate.
      return f;
    });
  }

  const startWithFiles = useCallback(
    (dropped: DroppedFile[]) => {
      if (dropped.length === 0) return;
      const initial = initialIngestable(dropped);
      setFiles(initial);
      void runHashingPipeline(initial);
    },
    [runHashingPipeline],
  );

  const handleDrop = useCallback(
    async (e: React.DragEvent) => {
      e.preventDefault();
      dragCounter.current = 0;
      setDragOver(false);
      const dropped = await filesFromDrop(e.dataTransfer);
      startWithFiles(dropped);
    },
    [startWithFiles],
  );

  const handleBrowse = useCallback(() => {
    const input = document.createElement("input");
    input.type = "file";
    input.multiple = true;
    input.webkitdirectory = true;
    input.onchange = async () => {
      const picked = Array.from(input.files ?? []);
      if (picked.length === 0) return;
      const dropped: DroppedFile[] = picked.map((f) => {
        const fileWithPath = f as File & { webkitRelativePath?: string };
        return {
          file: f,
          path: fileWithPath.webkitRelativePath || f.name,
        };
      });
      startWithFiles(dropped);
    };
    input.click();
  }, [startWithFiles]);

  const handleUrlSubmit = useCallback(() => {
    const trimmed = url.trim();
    if (!trimmed) return;
    navigate(`/pipeline?url=${encodeURIComponent(trimmed)}`);
  }, [navigate, url]);

  const toggleSelected = useCallback((id: string) => {
    setFiles((prev) => prev.map((f) => (f.id === id ? { ...f, selected: !f.selected } : f)));
  }, []);

  const selectAllNonDupe = useCallback(() => {
    setFiles((prev) =>
      prev.map((f) => ({
        ...f,
        selected: f.status === "unique" || f.status === "unrecognised" || f.status === "checking",
      })),
    );
  }, []);

  const handleConfirm = useCallback(() => {
    const candidates = files.filter((f) => f.selected && f.hash && f.status !== "error");
    if (candidates.length === 0) return;

    const uploadFiles: HashedFile[] = candidates.map((f) => ({
      file: f.file,
      hash: f.hash!,
    }));

    // Hand the actual upload off to the pipeline container via router
    // state — File objects survive history's structured-clone, so we
    // don't need a separate stash. Client-upload progress will render
    // as the "Uploading" stage on the pipeline page; once the server
    // returns a job_id the page transitions to SSE-driven phases.
    navigate("/pipeline", {
      state: { uploadFiles, stableJobId: crypto.randomUUID() },
    });
    setFiles([]);
  }, [files, navigate]);

  const handleCircleClick = useCallback(() => {
    if (hasActivePipeline) {
      navigate("/pipeline");
    } else {
      setExpanded(true);
    }
  }, [hasActivePipeline, navigate]);

  // ---- Derived state ----

  const isCircle = !expanded;
  const showContent = expanded;
  const hasFiles = files.length > 0;
  const selectedCount = files.filter((f) => f.selected).length;
  const checkingCount = files.filter((f) => f.status === "checking").length;
  const dupBatchCount = files.filter((f) => f.status === "duplicate-in-batch").length;
  const dupVaultCount = files.filter((f) => f.status === "duplicate-in-vault").length;
  const unrecognisedCount = files.filter((f) => f.status === "unrecognised").length;
  const totalSize = files.reduce((s, f) => s + f.file.size, 0);

  // ---- Transition ----

  const shellSpring = shouldAnimate
    ? { type: "spring" as const, stiffness: 300, damping: 28, mass: 0.6 }
    : { duration: 0 };

  const shellClass = isCircle
    ? "w-12 h-12 border border-dashed border-ink-border bg-transparent cursor-pointer"
    : "w-full max-w-[800px] border border-solid border-gold-dim bg-ink-raised overflow-hidden";

  // ---- Render ----

  return (
    <div className="w-full flex justify-center" ref={zoneRef}>
      <motion.div
        layout
        layoutId={LAYOUT_ID}
        transition={shellSpring}
        animate={{ borderRadius: isCircle ? 24 : 4 }}
        onClick={isCircle ? handleCircleClick : undefined}
        className={`relative ${shellClass}`}
        onDragEnter={
          showContent
            ? (e: React.DragEvent) => {
                e.preventDefault();
                dragCounter.current++;
                setDragOver(true);
              }
            : undefined
        }
        onDragOver={showContent ? (e: React.DragEvent) => e.preventDefault() : undefined}
        onDragLeave={
          showContent
            ? (e: React.DragEvent) => {
                e.preventDefault();
                dragCounter.current--;
                if (dragCounter.current <= 0) {
                  dragCounter.current = 0;
                  setDragOver(false);
                }
              }
            : undefined
        }
        onDrop={showContent ? handleDrop : undefined}
      >
        <motion.span
          animate={{ opacity: isCircle ? 1 : 0 }}
          transition={shouldAnimate ? { duration: 0.1, ease: [0.25, 1, 0.5, 1] } : { duration: 0 }}
          className="absolute inset-0 flex items-center justify-center pointer-events-none select-none"
        >
          <span className="font-mono text-[length:var(--text-body)] text-warm-ghost leading-none">
            +
          </span>
          {hasActivePipeline && (
            <span className="absolute -top-1 -right-1 w-3 h-3 rounded-full bg-gold animate-[pulse-fade_1.6s_ease-in-out_infinite]" />
          )}
        </motion.span>

        <motion.div
          animate={{ opacity: showContent ? 1 : 0 }}
          transition={
            shouldAnimate
              ? { duration: 0.15, ease: [0.25, 1, 0.5, 1], delay: showContent ? 0.12 : 0 }
              : { duration: 0 }
          }
          className={showContent ? "" : "pointer-events-none"}
        >
          {/* Expanded zone */}
          {expanded && (
            <>
              {hasFiles ? (
                /* ── With files selected ── */
                <div className="px-10 py-8">
                  <div className="flex flex-wrap items-center gap-x-4 gap-y-1.5 font-mono text-[length:var(--text-chrome)] tracking-[0.06em] text-warm-ghost mb-3">
                    <span>
                      {selectedCount} / {files.length} selected
                    </span>
                    <span>{formatSize(totalSize)}</span>
                    {checkingCount > 0 && (
                      <span className="text-gold-dim">{checkingCount} hashing</span>
                    )}
                    {dupBatchCount > 0 && (
                      <span className="text-warm-faint">{dupBatchCount} dup in batch</span>
                    )}
                    {dupVaultCount > 0 && (
                      <span className="text-warm-faint">{dupVaultCount} already in vault</span>
                    )}
                    {unrecognisedCount > 0 && (
                      <span className="text-warm-faint">{unrecognisedCount} unrecognised</span>
                    )}
                  </div>

                  <ScrollArea className="h-[320px] rounded-sm border border-ink-subtle">
                    <ul className="divide-y divide-ink-subtle">
                      {files.map((f) => (
                        <FileRow key={f.id} item={f} onToggle={toggleSelected} />
                      ))}
                    </ul>
                  </ScrollArea>

                  <div className="mt-6 pt-5 border-t border-ink-subtle">
                    <div className="flex items-center justify-center gap-2">
                      <Button
                        variant="ghost"
                        size="xs"
                        onClick={() => handleConfirm()}
                        disabled={selectedCount === 0 || checkingCount > 0}
                        className="font-mono text-[length:var(--text-chrome)] tracking-[0.1em]
                                   text-gold hover:text-gold-hover hover:bg-transparent
                                   disabled:text-warm-ghost disabled:cursor-not-allowed
                                   rounded-sm h-auto px-3 py-0.5"
                      >
                        ingest {selectedCount} file{selectedCount !== 1 ? "s" : ""}
                      </Button>
                      {(dupBatchCount > 0 || dupVaultCount > 0) && (
                        <Button
                          variant="ghost"
                          size="xs"
                          onClick={selectAllNonDupe}
                          className="font-mono text-[length:var(--text-chrome)] tracking-[0.1em]
                                     text-warm-ghost hover:text-warm-faint hover:bg-transparent
                                     rounded-sm h-auto px-3 py-0.5"
                        >
                          deselect duplicates
                        </Button>
                      )}
                      <Button
                        variant="ghost"
                        size="xs"
                        onClick={handleBrowse}
                        className="font-mono text-[length:var(--text-chrome)] tracking-[0.1em]
                                   text-warm-ghost hover:text-warm-faint hover:bg-transparent
                                   rounded-sm h-auto px-3 py-0.5"
                      >
                        replace
                      </Button>
                    </div>
                  </div>
                </div>
              ) : (
                /* ── Empty: generous drop target ── */
                <div className="px-10 py-14 flex flex-col items-center justify-center gap-6 min-h-[500px]">
                  <div className="text-center">
                    <p className="font-serif text-[length:var(--text-body)] text-warm-dim mb-1">
                      {isDragOver ? "drop to add to knowledge base" : "drop files or folders here"}
                    </p>
                    <p className="font-mono text-[length:var(--text-chrome)] tracking-[0.06em] text-warm-ghost">
                      or use the field below
                    </p>
                  </div>

                  <div className="w-full max-w-[420px] flex items-center gap-2">
                    <Input
                      className="flex-1 border-ink-border bg-transparent dark:bg-transparent
                                 font-mono text-[length:var(--text-chrome)] tracking-[0.08em]
                                 text-warm-faint placeholder:text-warm-ghost
                                 caret-gold focus-visible:ring-0 focus-visible:border-gold-dim
                                 h-8 py-0 px-3 rounded-sm"
                      placeholder="paste a link and press Enter"
                      value={url}
                      onChange={(e) => setUrl(e.target.value)}
                      onKeyDown={(e) => e.key === "Enter" && handleUrlSubmit()}
                    />
                    {url.trim() && (
                      <span
                        className="font-mono text-[length:var(--text-chrome)] text-warm-ghost select-none shrink-0"
                        title="Press Enter to ingest this URL"
                      >
                        ↵
                      </span>
                    )}
                  </div>

                  <button
                    onClick={handleBrowse}
                    title="Browse for a folder"
                    className="font-mono text-[length:var(--text-chrome)] tracking-[0.1em]
                               text-gold-dim hover:text-gold transition-colors
                               bg-transparent border-0 cursor-pointer"
                  >
                    or browse for a folder
                  </button>
                </div>
              )}
            </>
          )}
        </motion.div>
      </motion.div>
    </div>
  );
}

/** Status glyph + label per FileStatus. Kept inline in the row so the
 *  styling lives next to its semantics. */
function statusIndicator(status: FileStatus): { glyph: string; label: string; className: string } {
  switch (status) {
    case "checking":
      return {
        glyph: "◌",
        label: "checking…",
        className: "text-gold-dim animate-[pulse-fade_1.6s_ease-in-out_infinite]",
      };
    case "unique":
      return { glyph: "◉", label: "unique", className: "text-warm-dim" };
    case "duplicate-in-batch":
      return { glyph: "◯", label: "duplicate in batch", className: "text-warm-faint" };
    case "duplicate-in-vault":
      return { glyph: "⊘", label: "already in vault", className: "text-warm-faint" };
    case "unrecognised":
      return { glyph: "⚠", label: "unrecognised format", className: "text-warm-faint" };
    case "error":
      return { glyph: "✗", label: "error", className: "text-warm-faint" };
  }
}

function FileRow({ item, onToggle }: { item: IngestableFile; onToggle: (id: string) => void }) {
  const { glyph, label, className } = statusIndicator(item.status);
  const isDupe = item.status === "duplicate-in-batch" || item.status === "duplicate-in-vault";
  return (
    <li
      className={`flex items-center gap-3 px-3 py-1.5 transition-opacity ${
        isDupe && !item.selected ? "opacity-50" : ""
      }`}
    >
      <Checkbox
        checked={item.selected}
        onCheckedChange={() => onToggle(item.id)}
        aria-label={item.selected ? "Click to exclude" : "Click to include"}
        className="shrink-0"
      />
      <span
        className="font-serif text-[length:var(--text-small)] text-warm-dim truncate flex-1 min-w-0"
        title={item.path}
      >
        {item.path}
      </span>
      <span className="font-mono text-[length:var(--text-chrome)] tracking-[0.06em] text-warm-ghost shrink-0 w-16 text-right">
        {formatSize(item.file.size)}
      </span>
      <span
        className="font-mono text-[length:var(--text-chrome)] tracking-[0.06em] text-warm-ghost shrink-0 w-14 truncate"
        title={item.ext || "no ext"}
      >
        {item.ext || "—"}
      </span>
      <span
        className={`font-mono text-[length:var(--text-chrome)] tracking-[0.06em] shrink-0 w-44 truncate flex items-center gap-1.5 ${className}`}
        title={item.error ?? label}
      >
        <span className="shrink-0">{glyph}</span>
        <span className="truncate">{label}</span>
      </span>
    </li>
  );
}

// web/src/lib/components/ingestion-flow.svelte
<script lang="ts">
  import { goto } from "$app/navigation";
  import { onMount } from "svelte";
  import { cubicOut } from "svelte/easing";
  import { fade } from "svelte/transition";

  import { checkDupes, hashFile, type HashedFile } from "$lib/api/ingest";
  import { Button } from "$lib/components/ui/button";
  import { Input } from "$lib/components/ui/input";
  import type { DroppedFile } from "$lib/types";

  const RECOGNISED_EXTS = new Set([
    ".md",
    ".markdown",
    ".txt",
    ".text",
    ".pdf",
    ".docx",
    ".doc",
    ".pptx",
    ".ppt",
    ".xlsx",
    ".xls",
    ".csv",
    ".json",
    ".xml",
    ".html",
    ".htm",
    ".epub",
    ".rtf",
    ".odt",
  ]);
  const HASH_CONCURRENCY = 4;

  type FileStatus =
    | "checking"
    | "unique"
    | "duplicate-in-batch"
    | "duplicate-in-vault"
    | "unrecognised"
    | "error";

  interface IngestableFile {
    id: string;
    file: File;
    path: string;
    ext: string;
    status: FileStatus;
    hash?: string;
    selected: boolean;
    error?: string;
  }

  let {
    hasActivePipeline,
    usesR2,
  }: {
    hasActivePipeline: boolean;
    usesR2: boolean;
  } = $props();

  let expanded = $state(false);
  let isDragOver = $state(false);
  let url = $state("");
  let files = $state<IngestableFile[]>([]);
  let dragCounter = 0;
  let hashRunId = 0;
  let zone: HTMLDivElement;

  const hasFiles = $derived(files.length > 0);
  const selectedCount = $derived(files.filter((file) => file.selected).length);
  const checkingCount = $derived(
    files.filter((file) => file.status === "checking").length,
  );
  const dupBatchCount = $derived(
    files.filter((file) => file.status === "duplicate-in-batch").length,
  );
  const dupVaultCount = $derived(
    files.filter((file) => file.status === "duplicate-in-vault").length,
  );
  const unrecognisedCount = $derived(
    files.filter((file) => file.status === "unrecognised").length,
  );
  const totalSize = $derived(
    files.reduce((total, file) => total + file.file.size, 0),
  );

  function formatSize(bytes: number): string {
    if (bytes < 1024) return `${bytes} B`;
    if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
    return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
  }

  function extOf(name: string): string {
    return name.includes(".") ? `.${name.split(".").pop()?.toLowerCase()}` : "";
  }

  async function filesFromDrop(
    dataTransfer: DataTransfer,
  ): Promise<DroppedFile[]> {
    const entries = Array.from(dataTransfer.items)
      .map((item) => item.webkitGetAsEntry?.())
      .filter((entry): entry is FileSystemEntry => entry != null);

    if (entries.length > 0) return collectAll(entries, "");
    return Array.from(dataTransfer.files).map((file) => ({
      file,
      path: file.name,
    }));
  }

  async function collectAll(
    entries: FileSystemEntry[],
    prefix: string,
  ): Promise<DroppedFile[]> {
    const results: DroppedFile[] = [];
    for (const entry of entries) {
      if (entry.isFile) {
        const fileEntry = entry as FileSystemFileEntry;
        const file = await new Promise<File>((resolve, reject) =>
          fileEntry.file(resolve, reject),
        );
        results.push({
          file,
          path: prefix ? `${prefix}/${entry.name}` : entry.name,
        });
      } else if (entry.isDirectory) {
        const directory = entry as FileSystemDirectoryEntry;
        const reader = directory.createReader();
        const children: FileSystemEntry[] = [];
        let batch: FileSystemEntry[];
        do {
          batch = await new Promise((resolve) =>
            reader.readEntries((items) => resolve(items)),
          );
          children.push(...batch);
        } while (batch.length > 0);
        const path = prefix ? `${prefix}/${entry.name}` : entry.name;
        results.push(...(await collectAll(children, path)));
      }
    }
    return results;
  }

  function initialIngestable(dropped: DroppedFile[]): IngestableFile[] {
    return dropped.map(({ file, path }) => {
      const ext = extOf(file.name);
      const recognised = ext === "" || RECOGNISED_EXTS.has(ext);
      return {
        id: crypto.randomUUID(),
        file,
        path,
        ext,
        status: recognised ? "checking" : "unrecognised",
        selected: true,
      };
    });
  }

  function close() {
    expanded = false;
    files = [];
    hashRunId += 1;
    url = "";
  }

  onMount(() => {
    let dragDepth = 0;
    const handleMouseDown = (event: MouseEvent) => {
      if (expanded && zone && !zone.contains(event.target as Node)) close();
    };
    const handleKeydown = (event: KeyboardEvent) => {
      if (expanded && event.key === "Escape") close();
    };
    const handleDragEnter = (event: DragEvent) => {
      event.preventDefault();
      dragDepth += 1;
      if (dragDepth > 0 && !expanded) expanded = true;
    };
    const handleDragLeave = (event: DragEvent) => {
      event.preventDefault();
      dragDepth = Math.max(0, dragDepth - 1);
    };
    const handleDragOver = (event: DragEvent) => event.preventDefault();
    // Deliberately do not stop propagation. The innermost drop handler must
    // receive the DataTransfer before this document-level cleanup runs.
    const handleDocumentDrop = (event: DragEvent) => {
      event.preventDefault();
      dragDepth = 0;
    };

    document.addEventListener("mousedown", handleMouseDown);
    window.addEventListener("keydown", handleKeydown);
    document.addEventListener("dragenter", handleDragEnter);
    document.addEventListener("dragleave", handleDragLeave);
    document.addEventListener("dragover", handleDragOver);
    document.addEventListener("drop", handleDocumentDrop);
    return () => {
      document.removeEventListener("mousedown", handleMouseDown);
      window.removeEventListener("keydown", handleKeydown);
      document.removeEventListener("dragenter", handleDragEnter);
      document.removeEventListener("dragleave", handleDragLeave);
      document.removeEventListener("dragover", handleDragOver);
      document.removeEventListener("drop", handleDocumentDrop);
    };
  });

  function applyHash(
    current: IngestableFile[],
    id: string,
    hash: string,
  ): IngestableFile[] {
    const duplicate = current.some(
      (file) => file.id !== id && file.hash === hash,
    );
    return current.map((file) =>
      file.id === id
        ? {
            ...file,
            hash,
            status: duplicate ? "duplicate-in-batch" : "unique",
            selected: !duplicate,
          }
        : file,
    );
  }

  async function runHashingPipeline(initial: IngestableFile[]) {
    hashRunId += 1;
    const runId = hashRunId;
    let cursor = 0;

    async function worker() {
      while (true) {
        const index = cursor++;
        if (index >= initial.length) return;
        const item = initial[index];
        if (item.status !== "checking") continue;
        try {
          const hash = await hashFile(item.file);
          if (hashRunId !== runId) return;
          files = applyHash(files, item.id, hash);
        } catch (error) {
          if (hashRunId !== runId) return;
          files = files.map((file) =>
            file.id === item.id
              ? {
                  ...file,
                  status: "error",
                  error: error instanceof Error ? error.message : "hash failed",
                }
              : file,
          );
        }
      }
    }

    await Promise.all(
      Array.from(
        { length: Math.min(HASH_CONCURRENCY, initial.length) },
        worker,
      ),
    );
    if (hashRunId !== runId) return;

    const hashes = files
      .filter(
        (file) =>
          file.status === "unique" || file.status === "duplicate-in-batch",
      )
      .map((file) => file.hash!)
      .filter(Boolean);
    const existing = await checkDupes(Array.from(new Set(hashes)));
    if (hashRunId !== runId || existing.size === 0) return;
    files = files.map((file) =>
      file.hash && existing.has(file.hash)
        ? { ...file, status: "duplicate-in-vault", selected: false }
        : file,
    );
  }

  function startWithFiles(dropped: DroppedFile[]) {
    if (dropped.length === 0) return;
    const initial = initialIngestable(dropped);
    files = initial;
    void runHashingPipeline(initial);
  }

  async function handleDrop(event: DragEvent) {
    event.preventDefault();
    dragCounter = 0;
    isDragOver = false;
    startWithFiles(await filesFromDrop(event.dataTransfer!));
  }

  function handleBrowse() {
    const input = document.createElement("input");
    input.type = "file";
    input.multiple = true;
    input.webkitdirectory = true;
    input.onchange = () => {
      const picked = Array.from(input.files ?? []);
      startWithFiles(
        picked.map((file) => ({
          file,
          path:
            (file as File & { webkitRelativePath?: string })
              .webkitRelativePath || file.name,
        })),
      );
    };
    input.click();
  }

  function submitUrl() {
    const trimmed = url.trim();
    if (trimmed) void goto(`/pipeline?url=${encodeURIComponent(trimmed)}`);
  }

  function toggleSelected(id: string) {
    files = files.map((file) =>
      file.id === id ? { ...file, selected: !file.selected } : file,
    );
  }

  function deselectDuplicates() {
    files = files.map((file) => ({
      ...file,
      selected:
        file.status === "unique" ||
        file.status === "unrecognised" ||
        file.status === "checking",
    }));
  }

  function confirm() {
    const uploadFiles: HashedFile[] = files
      .filter((file) => file.selected && file.hash && file.status !== "error")
      .map((item) => ({ file: item.file, hash: item.hash! }));
    if (uploadFiles.length === 0) return;

    void goto("/pipeline", {
      state: {
        uploadFiles,
        stableJobId: crypto.randomUUID(),
        uploadMode: usesR2 ? "staged" : "direct",
      },
    });
    files = [];
  }

  function handleCircleClick() {
    if (hasActivePipeline) void goto("/pipeline");
    else expanded = true;
  }

  function statusIndicator(status: FileStatus) {
    switch (status) {
      case "checking":
        return {
          glyph: "◌",
          label: "checking…",
          className:
            "text-gold-dim animate-[pulse-fade_1.6s_ease-in-out_infinite]",
        };
      case "unique":
        return {
          glyph: "◉",
          label: "unique",
          className: "text-warm-dim",
        };
      case "duplicate-in-batch":
        return {
          glyph: "◯",
          label: "duplicate in batch",
          className: "text-warm-faint",
        };
      case "duplicate-in-vault":
        return {
          glyph: "⊘",
          label: "already in vault",
          className: "text-warm-faint",
        };
      case "unrecognised":
        return {
          glyph: "⚠",
          label: "unrecognised format",
          className: "text-warm-faint",
        };
      case "error":
        return {
          glyph: "✗",
          label: "error",
          className: "text-warm-faint",
        };
    }
  }
</script>

<div class="flex w-full flex-col items-center" bind:this={zone}>
  <!-- svelte-ignore a11y_no_noninteractive_tabindex - the shell is a keyboard button only while collapsed -->
  <div
    role={expanded ? undefined : "button"}
    tabindex={expanded ? undefined : 0}
    aria-label={expanded
      ? "source ingestion"
      : hasActivePipeline
        ? "view active pipeline"
        : "add sources"}
    onclick={expanded ? undefined : handleCircleClick}
    onkeydown={(event) => {
      if (!expanded && (event.key === "Enter" || event.key === " ")) {
        event.preventDefault();
        handleCircleClick();
      }
    }}
    ondragenter={expanded
      ? (event) => {
          event.preventDefault();
          dragCounter += 1;
          isDragOver = true;
        }
      : undefined}
    ondragover={expanded ? (event) => event.preventDefault() : undefined}
    ondragleave={expanded
      ? (event) => {
          event.preventDefault();
          dragCounter -= 1;
          if (dragCounter <= 0) {
            dragCounter = 0;
            isDragOver = false;
          }
        }
      : undefined}
    ondrop={expanded ? handleDrop : undefined}
    class={`relative transition-[width,height,border-radius,border-color,background-color] duration-300 ease-out ${
      expanded
        ? "w-full max-w-[800px] overflow-hidden rounded-sm border border-solid border-gold-dim bg-ink-raised"
        : "h-12 w-12 cursor-pointer rounded-full border border-dashed border-ink-border bg-transparent"
    }`}
  >
    {#if !expanded}
      <span
        class="absolute inset-0 flex items-center justify-center font-mono text-[length:var(--text-body)] leading-none text-warm-ghost select-none"
        transition:fade={{ duration: 100 }}
      >
        +
        {#if hasActivePipeline}
          <span
            class="absolute -top-1 -right-1 h-3 w-3 animate-[pulse-fade_1.6s_ease-in-out_infinite] rounded-full bg-gold"
          ></span>
        {/if}
      </span>
    {:else}
      <div
        in:fade={{ duration: 180, delay: 100, easing: cubicOut }}
        out:fade={{ duration: 100 }}
      >
        {#if hasFiles}
          <div class="px-5 py-6 md:px-10 md:py-8">
            <div
              class="mb-3 flex flex-wrap items-center gap-x-4 gap-y-1.5 font-mono text-[length:var(--text-chrome)] tracking-[0.06em] text-warm-ghost"
            >
              <span>{selectedCount} / {files.length} selected</span>
              <span>{formatSize(totalSize)}</span>
              {#if checkingCount > 0}
                <span class="text-gold-dim">{checkingCount} hashing</span>
              {/if}
              {#if dupBatchCount > 0}
                <span class="text-warm-faint">{dupBatchCount} dup in batch</span
                >
              {/if}
              {#if dupVaultCount > 0}
                <span class="text-warm-faint"
                  >{dupVaultCount} already in vault</span
                >
              {/if}
              {#if unrecognisedCount > 0}
                <span class="text-warm-faint"
                  >{unrecognisedCount} unrecognised</span
                >
              {/if}
            </div>

            <div
              class="h-[320px] overflow-y-auto rounded-sm border border-ink-subtle"
            >
              <ul class="divide-y divide-ink-subtle">
                {#each files as item (item.id)}
                  {@const indicator = statusIndicator(item.status)}
                  {@const isDupe =
                    item.status === "duplicate-in-batch" ||
                    item.status === "duplicate-in-vault"}
                  <li
                    class={`flex items-center gap-3 px-3 py-1.5 transition-opacity ${isDupe && !item.selected ? "opacity-50" : ""}`}
                  >
                    <input
                      type="checkbox"
                      checked={item.selected}
                      onchange={() => toggleSelected(item.id)}
                      aria-label={item.selected
                        ? "Click to exclude"
                        : "Click to include"}
                      class="h-4 w-4 shrink-0 accent-gold"
                    />
                    <span
                      class="min-w-0 flex-1 truncate font-serif text-[length:var(--text-small)] text-warm-dim"
                      title={item.path}
                    >
                      {item.path}
                    </span>
                    <span
                      class="w-16 shrink-0 text-right font-mono text-[length:var(--text-chrome)] tracking-[0.06em] text-warm-ghost"
                    >
                      {formatSize(item.file.size)}
                    </span>
                    <span
                      class="w-14 shrink-0 truncate font-mono text-[length:var(--text-chrome)] tracking-[0.06em] text-warm-ghost"
                      title={item.ext || "no ext"}
                    >
                      {item.ext || "—"}
                    </span>
                    <span
                      class={`flex w-44 shrink-0 items-center gap-1.5 truncate font-mono text-[length:var(--text-chrome)] tracking-[0.06em] ${indicator.className}`}
                      title={item.error ?? indicator.label}
                    >
                      <span class="shrink-0">{indicator.glyph}</span>
                      <span class="truncate">{indicator.label}</span>
                    </span>
                  </li>
                {/each}
              </ul>
            </div>

            <div class="mt-6 border-t border-ink-subtle pt-5">
              <div class="flex flex-wrap items-center justify-center gap-2">
                <Button
                  variant="ghost"
                  size="xs"
                  onclick={confirm}
                  disabled={selectedCount === 0 || checkingCount > 0}
                  class="h-auto rounded-sm px-3 py-0.5 font-mono text-[length:var(--text-chrome)] tracking-[0.1em] text-gold hover:bg-transparent hover:text-gold-hover disabled:cursor-not-allowed disabled:text-warm-ghost"
                >
                  ingest {selectedCount} file{selectedCount !== 1 ? "s" : ""}
                </Button>
                {#if dupBatchCount > 0 || dupVaultCount > 0}
                  <Button
                    variant="ghost"
                    size="xs"
                    onclick={deselectDuplicates}
                    class="h-auto rounded-sm px-3 py-0.5 font-mono text-[length:var(--text-chrome)] tracking-[0.1em] text-warm-ghost hover:bg-transparent hover:text-warm-faint"
                  >
                    deselect duplicates
                  </Button>
                {/if}
                <Button
                  variant="ghost"
                  size="xs"
                  onclick={handleBrowse}
                  class="h-auto rounded-sm px-3 py-0.5 font-mono text-[length:var(--text-chrome)] tracking-[0.1em] text-warm-ghost hover:bg-transparent hover:text-warm-faint"
                >
                  replace
                </Button>
              </div>
            </div>
          </div>
        {:else}
          <div
            class="flex min-h-[500px] flex-col items-center justify-center gap-6 px-5 py-14 md:px-10"
          >
            <div class="text-center">
              <p
                class="mb-1 font-serif text-[length:var(--text-body)] text-warm-dim"
              >
                {isDragOver
                  ? "drop to add to knowledge base"
                  : "drop files or folders here"}
              </p>
              <p
                class="font-mono text-[length:var(--text-chrome)] tracking-[0.06em] text-warm-ghost"
              >
                or use the field below
              </p>
            </div>

            <div class="flex w-full max-w-[420px] items-center gap-2">
              <Input
                bind:value={url}
                onkeydown={(event) => event.key === "Enter" && submitUrl()}
                class="h-8 flex-1 rounded-sm border-ink-border bg-transparent px-3 py-0 font-mono text-[length:var(--text-chrome)] tracking-[0.08em] text-warm-faint caret-gold placeholder:text-warm-ghost focus-visible:border-gold-dim focus-visible:ring-0 dark:bg-transparent"
                placeholder="paste a link and press Enter"
              />
              {#if url.trim()}
                <span
                  class="shrink-0 font-mono text-[length:var(--text-chrome)] text-warm-ghost select-none"
                  title="Press Enter to ingest this URL"
                >
                  ↵
                </span>
              {/if}
            </div>

            <button
              type="button"
              onclick={handleBrowse}
              title="Browse for a folder"
              class="cursor-pointer border-0 bg-transparent font-mono text-[length:var(--text-chrome)] tracking-[0.1em] text-gold-dim transition-colors hover:text-gold"
            >
              or browse for a folder
            </button>
          </div>
        {/if}
      </div>
    {/if}
  </div>

  {#if hasActivePipeline && !expanded}
    <a
      href="/pipeline"
      onclick={(event) => {
        event.preventDefault();
        void goto("/pipeline");
      }}
      class="mt-3 font-mono text-[length:var(--text-chrome)] tracking-[0.08em] text-gold-muted transition-colors hover:text-gold"
    >
      pipeline active · view progress →
    </a>
  {/if}
</div>
