// web/src/components/thinking-section.tsx
import { useState } from "react";
import { ChevronDown, ChevronRight, ListFilter, Search, Waypoints } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import type { SourceRef, ThinkingBlock } from "@/lib/types";
import { displayTitle } from "@/lib/utils";

interface ThinkingSectionProps {
  blocks: ThinkingBlock[];
  streaming: boolean;
  onCardClick: (src: SourceRef) => void;
  activeCard: string | null;
}

export function ThinkingSection({
  blocks,
  streaming,
  onCardClick,
  activeCard,
}: ThinkingSectionProps) {
  // null = user hasn't overridden, follow streaming state
  const [userOverride, setUserOverride] = useState<boolean | null>(null);
  const open = userOverride ?? streaming;

  if (blocks.length === 0 && !streaming) return null;

  const allSources = blocks.flatMap((b) => b.sources);
  const articles = allSources.filter((s) => s.type === "article").length;
  const raw = allSources.filter((s) => s.type === "raw").length;
  const searches = allSources.filter((s) => s.type === "search").length;
  const queries = allSources.filter((s) => s.type === "query").length;
  const links = allSources.filter((s) => s.type === "links").length;

  const summaryParts: string[] = [];
  if (searches) summaryParts.push(`${searches} search${searches !== 1 ? "es" : ""}`);
  if (queries) summaryParts.push(`${queries} filter${queries !== 1 ? "s" : ""}`);
  if (articles) summaryParts.push(`${articles} article${articles !== 1 ? "s" : ""} read`);
  if (raw) summaryParts.push(`${raw} source${raw !== 1 ? "s" : ""} read`);
  if (links) summaryParts.push(`${links} connection${links !== 1 ? "s" : ""} explored`);
  const summary = summaryParts.join(", ") || "no sources";

  return (
    <div className="mb-4">
      <Button
        variant="ghost"
        size="sm"
        onClick={() => setUserOverride(open ? false : true)}
        className="h-auto p-0 font-mono text-[length:var(--text-chrome)] tracking-[0.1em] text-gold-muted hover:text-gold hover:bg-transparent gap-1.5"
      >
        {open ? <ChevronDown size={10} /> : <ChevronRight size={10} />}
        {streaming ? (
          <span className="animate-[pulse-fade_1.6s_ease-in-out_infinite]">
            traversing knowledge base...
          </span>
        ) : (
          <span>{summary}</span>
        )}
      </Button>

      {open && (
        <div className="mt-2 border-l-2 border-interactive-ghost pl-3.5 space-y-3">
          <div className="relative z-[200] flex flex-wrap gap-[5px]">
            {blocks
              .flatMap((b) => b.sources)
              .map((src, i) => {
                if (src.type === "search")
                  return <SearchBadge key={`search:${i}:${src.label}`} query={src.label} />;
                if (src.type === "query")
                  return <FilterBadge key={`query:${i}:${src.label}`} summary={src.label} />;
                return (
                  <ArticleBadge
                    key={`${src.type}:${i}:${src.label}`}
                    label={src.label}
                    title={src.title}
                    thinking={src.thinking ?? undefined}
                    active={activeCard === src.label}
                    onClick={() => onCardClick(src)}
                    icon={
                      src.type === "links" ? (
                        <Waypoints size={9} className="mr-1.5 opacity-60" />
                      ) : undefined
                    }
                  />
                );
              })}
          </div>
        </div>
      )}
    </div>
  );
}

function SearchBadge({ query }: { query: string }) {
  return (
    <Badge
      variant="outline"
      className="cursor-default rounded-sm h-auto px-[9px] py-[3px] font-mono text-[length:var(--text-chrome)] tracking-[0.06em] whitespace-nowrap bg-ink-raised border-ink-border text-warm-ghost italic"
    >
      <Search size={9} className="mr-1.5 opacity-60" />
      {query}
    </Badge>
  );
}

function FilterBadge({ summary }: { summary: string }) {
  return (
    <Badge
      variant="outline"
      className="cursor-default rounded-sm h-auto px-[9px] py-[3px] font-mono text-[length:var(--text-chrome)] tracking-[0.06em] whitespace-nowrap bg-ink-raised border-ink-border text-warm-ghost italic"
    >
      <ListFilter size={9} className="mr-1.5 opacity-60" />
      {summary}
    </Badge>
  );
}

function ArticleBadge({
  label,
  title,
  thinking,
  active,
  onClick,
  icon,
}: {
  label: string;
  title?: string | null;
  thinking?: string;
  active: boolean;
  onClick?: () => void;
  icon?: React.ReactNode;
}) {
  return (
    <Badge
      variant="outline"
      onClick={onClick}
      title={thinking}
      className={`rounded-sm h-auto px-[9px] py-[3px] font-mono text-[length:var(--text-chrome)] tracking-[0.06em] whitespace-nowrap transition-all ${
        onClick ? "cursor-pointer" : "cursor-default"
      } ${
        active
          ? "border-gold-dim text-gold bg-interactive-dim"
          : "bg-ink-raised border-ink-border text-card-foreground hover:border-gold-dim hover:text-gold"
      }`}
      role={onClick ? "button" : undefined}
      tabIndex={onClick ? 0 : undefined}
      onKeyDown={
        onClick
          ? (e: React.KeyboardEvent) => {
              if (e.key === "Enter" || e.key === " ") {
                e.preventDefault();
                onClick();
              }
            }
          : undefined
      }
    >
      {icon}
      {displayTitle(label, title)}
    </Badge>
  );
}

// web/src/lib/components/thinking-section.svelte
<script lang="ts">
  import ChevronDown from "@lucide/svelte/icons/chevron-down";
  import ChevronRight from "@lucide/svelte/icons/chevron-right";

  import ArticleBadge from "$lib/components/article-badge.svelte";
  import FilterBadge from "$lib/components/filter-badge.svelte";
  import SearchBadge from "$lib/components/search-badge.svelte";
  import { Button } from "$lib/components/ui/button";
  import type { SourceRef, ThinkingBlock } from "$lib/types";

  let {
    blocks,
    streaming,
    onCardClick,
    activeCard,
  }: {
    blocks: ThinkingBlock[];
    streaming: boolean;
    onCardClick: (source: SourceRef) => void;
    activeCard: string | null;
  } = $props();

  let userOverride = $state<boolean | null>(null);
  const open = $derived(userOverride ?? streaming);
  const allSources = $derived(blocks.flatMap((block) => block.sources));
  const summary = $derived.by(() => {
    const settled = allSources.filter((source) => source.pending !== true);
    const articles = settled.filter(
      (source) => source.type === "article",
    ).length;
    const raw = settled.filter((source) => source.type === "raw").length;
    const webSearches = settled.filter(
      (source) => source.type === "search" && source.scope === "web",
    ).length;
    const searches =
      settled.filter((source) => source.type === "search").length - webSearches;
    const filters = settled.filter((source) => source.type === "query").length;
    const links = settled.filter((source) => source.type === "links").length;
    const parts: string[] = [];

    if (searches) parts.push(`${searches} search${searches === 1 ? "" : "es"}`);
    if (webSearches)
      parts.push(`${webSearches} web search${webSearches === 1 ? "" : "es"}`);
    if (filters) parts.push(`${filters} filter${filters === 1 ? "" : "s"}`);
    if (articles)
      parts.push(`${articles} article${articles === 1 ? "" : "s"} read`);
    if (raw) parts.push(`${raw} source${raw === 1 ? "" : "s"} read`);
    if (links)
      parts.push(`${links} connection${links === 1 ? "" : "s"} explored`);
    return parts.join(", ") || "no sources";
  });
</script>

{#if blocks.length > 0 || streaming}
  <div class="mb-4">
    <Button
      variant="ghost"
      size="sm"
      onclick={() => (userOverride = !open)}
      class="h-auto gap-1.5 p-0 font-mono text-[length:var(--text-chrome)] tracking-[0.1em] text-gold-muted hover:bg-transparent hover:text-gold"
    >
      {#if open}
        <ChevronDown size={10} />
      {:else}
        <ChevronRight size={10} />
      {/if}
      {#if streaming}
        <span class="animate-[pulse-fade_1.6s_ease-in-out_infinite]">
          traversing knowledge base...
        </span>
      {:else}
        <span>{summary}</span>
      {/if}
    </Button>

    {#if open}
      <div class="mt-2 space-y-3 border-l-2 border-interactive-ghost pl-3.5">
        <div class="relative z-[200] flex flex-wrap gap-[5px]">
          {#each allSources as source, index (`${source.type}:${index}:${source.label}`)}
            {#if source.type === "search"}
              <SearchBadge {source} />
            {:else if source.type === "query"}
              <FilterBadge
                summary={source.label}
                pending={source.pending === true}
              />
            {:else}
              <ArticleBadge
                {source}
                active={activeCard === source.label}
                onClick={source.pending ? undefined : () => onCardClick(source)}
              />
            {/if}
          {/each}
        </div>
      </div>
    {/if}
  </div>
{/if}
